### ISSUE TITLE
All cv1k games core dump on Ubuntu Jaunty with Mame 0.248

### ISSUE THREAD

**Issue by wwark** [mamedev/mame#10376]
You will find below the log:

```
Loading translation file /home/Mame/language/English/strings.mo
Reading translation file: 1 strings, original table at word offset 7, translated table at word offset 9
Loaded 0 translated string from file
Starting plugin data...
Attempting load of mame.ini
Parsing mame.ini
Attempting load of mame.ini
Parsing mame.ini
Available videodrivers: x11 wayland KMSDRM dummy 
Current Videodriver: x11
	Display #0
		Renderdrivers:
			    opengl (0x0)
			 opengles2 (0x0)
			  software (0x0)
Available audio drivers: 
	pulseaudio          
	alsa                
	sndio               
	pipewire            
	dsp                 
	disk                
	dummy               
Build version:      0.248 (unknown)
Build architecure:  
Build defines 1:    SDLMAME_UNIX=1 SDLMAME_X11=1 SDLMAME_LINUX=1 
Build defines 1:    LSB_FIRST=1 PTR64=1 
SDL/OpenGL defines: SDL_COMPILEDVERSION=2020 USE_OPENGL=1 
Compiler defines A: __GNUC__=11 __GNUC_MINOR__=2 __GNUC_PATCHLEVEL__=0 __VERSION__="11.2.0" 
Compiler defines B: __amd64__=1 __x86_64__=1 __unix__=1 
Compiler defines C: __USE_FORTIFY_LEVEL=0 
Enter init_monitors
Adding monitor screen0 (1920 x 1080)
Leave init_monitors
Enter sdlwindow_init
Using SDL multi-window OpenGL driver (SDL 2.0+)

Hints:
	SDL_FRAMEBUFFER_ACCELERATION             (NULL)
	SDL_RENDER_DRIVER                        (NULL)
	SDL_RENDER_OPENGL_SHADERS                (NULL)
	SDL_RENDER_SCALE_QUALITY                 (NULL)
	SDL_RENDER_VSYNC                         (NULL)
	SDL_VIDEO_X11_XVIDMODE                   (NULL)
	SDL_VIDEO_X11_XINERAMA                   (NULL)
	SDL_VIDEO_X11_XRANDR                     (NULL)
	SDL_GRAB_KEYBOARD                        (NULL)
	SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS         (NULL)
	SDL_IOS_IDLE_TIMER_DISABLED              (NULL)
	SDL_IOS_ORIENTATIONS                     (NULL)
	SDL_XINPUT_ENABLED                       (NULL)
	SDL_GAMECONTROLLERCONFIG                 (NULL)
	SDL_JOYSTICK_ALLOW_BACKGROUND_EVENTS     (NULL)
	SDL_ALLOW_TOPMOST                        (NULL)
	SDL_TIMER_RESOLUTION                     (NULL)
	SDL_RENDER_DIRECT3D_THREADSAFE           (NULL)
	SDL_VIDEO_ALLOW_SCREENSAVER              (NULL)
	SDL_ACCELEROMETER_AS_JOYSTICK            (NULL)
	SDL_MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK   (NULL)
	SDL_VIDEO_WIN_D3DCOMPILER                (NULL)
	SDL_VIDEO_WINDOW_SHARE_PIXEL_FORMAT      (NULL)
	SDL_VIDEO_MAC_FULLSCREEN_SPACES          (NULL)
	SDL_MOUSE_RELATIVE_MODE_WARP             (NULL)
	SDL_RENDER_DIRECT3D11_DEBUG              (NULL)
	SDL_VIDEO_HIGHDPI_DISABLED               (NULL)
	SDL_WINRT_PRIVACY_POLICY_URL             (NULL)
	SDL_WINRT_PRIVACY_POLICY_LABEL           (NULL)
	SDL_WINRT_HANDLE_BACK_BUTTON             (NULL)
Leave sdlwindow_init
Enter sdl_info::create
OpenGL: Intel
OpenGL: Mesa Intel(R) UHD Graphics 620 (KBL GT2)
OpenGL: 4.6 (Compatibility Profile) Mesa 22.0.5
OpenGL: texture rectangle supported
OpenGL: non-power-of-2 textures supported (new method)
OpenGL: vertex buffer supported
OpenGL: pixel buffers supported
OpenGL: framebuffer object supported
OpenGL: GLSL supported, but disabled
OpenGL: max texture size 16384 x 16384
Leave renderer_ogl::create
Audio: Start initialization
Audio: Driver is pulseaudio
Audio: frequency: 48000, channels: 2, samples: 256
sdl_create_buffers: creating stream buffer of 25600 bytes
Audio: End initialization
Keyboard: Start initialization
Input: Adding keyboard #1: System keyboard (device id: System keyboard)
Keyboard: Registered System keyboard
Keyboard: End initialization
Mouse: Start initialization
Input: Adding mouse #1: System mouse (device id: System mouse)
Mouse: Registered System mouse
Mouse: End initialization
Lightgun: Begin initialization
Lightgun: End initialization
Joystick: Start initialization
Joystick: End initialization
Searching font Liberation Sans in -/home/Mame/fonts path/s
Matching font: 0x5616ad2d5340
:: invalid BIOS "0", reverting to default
WARNING: the machine might not run correctly.
Optional memory region ':screen' not found
Starting No Driver Loaded ':'
  (missing dependencies; rescheduling)
Starting Video Screen ':screen'
Starting No Driver Loaded ':'
Checking for icons in directory icons
No candidate icons found for machines
Attempting to parse: default.cfg
Attempting to parse: ___empty.cfg
Soft reset
drc_cache: RWX pages supported
OpenGL: VBO supported
OpenGL: PBO supported
OpenGL: FBO supported
OpenGL: using vid filter: 1
drc_cache: RWX pages supported
drc_cache: RWX pages supported
unzip: opened archive file /home/Mame/Mame_Arcade/roms/mushisam.zip
unzip: found /home/Mame/Mame_Arcade/roms/mushisam.zip ECD
unzip: /home/Mame/Mame_Arcade/roms/mushisam.zip has no ZIP64 ECD locator
unzip: read /home/Mame/Mame_Arcade/roms/mushisam.zip central directory
unzip: closing archive file /home/Mame/Mame_Arcade/roms/mushisam.zip and sending to cache
unzip: found /home/Mame/Mame_Arcade/roms/mushisam.zip in cache
unzip: closing archive file /home/Mame/Mame_Arcade/roms/mushisam.zip and sending to cache
unzip: found /home/Mame/Mame_Arcade/roms/mushisam.zip in cache
unzip: closing archive file /home/Mame/Mame_Arcade/roms/mushisam.zip and sending to cache
unzip: found /home/Mame/Mame_Arcade/roms/mushisam.zip in cache
unzip: closing archive file /home/Mame/Mame_Arcade/roms/mushisam.zip and sending to cache
drc_cache: RWX pages supported
drc_cache: RWX pages supported
sdl_kill: closing audio
Enter sdlwindow_exit
Leave sdlwindow_exit
Attempting load of mame.ini
Parsing mame.ini
Attempting load of mame.ini
Parsing mame.ini
Attempting load of vertical.ini
Attempting load of arcade.ini
drc_cache: RWX pages supported
Attempting load of raster.ini
Attempting load of source/cv1k.ini
Attempting load of mushisam.ini
drc_cache: RWX pages supported
Available videodrivers: x11 wayland KMSDRM dummy 
Current Videodriver: x11
	Display #0
		Renderdrivers:
			    opengl (0x0)
			 opengles2 (0x0)
			  software (0x0)
Available audio drivers: 
	pulseaudio          
	alsa                
	sndio               
	pipewire            
	dsp                 
	disk                
	dummy               
Build version:      0.248 (unknown)
Build architecure:  
Build defines 1:    SDLMAME_UNIX=1 SDLMAME_X11=1 SDLMAME_LINUX=1 
Build defines 1:    LSB_FIRST=1 PTR64=1 
SDL/OpenGL defines: SDL_COMPILEDVERSION=2020 USE_OPENGL=1 
Compiler defines A: __GNUC__=11 __GNUC_MINOR__=2 __GNUC_PATCHLEVEL__=0 __VERSION__="11.2.0" 
Compiler defines B: __amd64__=1 __x86_64__=1 __unix__=1 
Compiler defines C: __USE_FORTIFY_LEVEL=0 
Enter init_monitors
Adding monitor screen0 (1920 x 1080)
Leave init_monitors
Enter sdlwindow_init
Using SDL multi-window OpenGL driver (SDL 2.0+)

Hints:
	SDL_FRAMEBUFFER_ACCELERATION             (NULL)
	SDL_RENDER_DRIVER                        (NULL)
	SDL_RENDER_OPENGL_SHADERS                (NULL)
	SDL_RENDER_SCALE_QUALITY                 (NULL)
	SDL_RENDER_VSYNC                         (NULL)
	SDL_VIDEO_X11_XVIDMODE                   (NULL)
	SDL_VIDEO_X11_XINERAMA                   (NULL)
	SDL_VIDEO_X11_XRANDR                     (NULL)
	SDL_GRAB_KEYBOARD                        (NULL)
	SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS         (NULL)
	SDL_IOS_IDLE_TIMER_DISABLED              (NULL)
	SDL_IOS_ORIENTATIONS                     (NULL)
	SDL_XINPUT_ENABLED                       (NULL)
	SDL_GAMECONTROLLERCONFIG                 (NULL)
	SDL_JOYSTICK_ALLOW_BACKGROUND_EVENTS     (NULL)
	SDL_ALLOW_TOPMOST                        (NULL)
	SDL_TIMER_RESOLUTION                     (NULL)
	SDL_RENDER_DIRECT3D_THREADSAFE           (NULL)
	SDL_VIDEO_ALLOW_SCREENSAVER              (NULL)
	SDL_ACCELEROMETER_AS_JOYSTICK            0
	SDL_MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK   (NULL)
	SDL_VIDEO_WIN_D3DCOMPILER                (NULL)
	SDL_VIDEO_WINDOW_SHARE_PIXEL_FORMAT      (NULL)
	SDL_VIDEO_MAC_FULLSCREEN_SPACES          (NULL)
	SDL_MOUSE_RELATIVE_MODE_WARP             (NULL)
	SDL_RENDER_DIRECT3D11_DEBUG              (NULL)
	SDL_VIDEO_HIGHDPI_DISABLED               (NULL)
	SDL_WINRT_PRIVACY_POLICY_URL             (NULL)
	SDL_WINRT_PRIVACY_POLICY_LABEL           (NULL)
	SDL_WINRT_HANDLE_BACK_BUTTON             (NULL)
Leave sdlwindow_init
Enter sdl_info::create
Leave renderer_ogl::create
Audio: Start initialization
Audio: Driver is pulseaudio
Audio: frequency: 48000, channels: 2, samples: 256
sdl_create_buffers: creating stream buffer of 25600 bytes
Audio: End initialization
Keyboard: Start initialization
Input: Adding keyboard #1: System keyboard (device id: System keyboard)
Keyboard: Registered System keyboard
Keyboard: End initialization
Mouse: Start initialization
Input: Adding mouse #1: System mouse (device id: System mouse)
Mouse: Registered System mouse
Mouse: End initialization
Lightgun: Begin initialization
Lightgun: End initialization
Joystick: Start initialization
Joystick: End initialization
Searching font Liberation Sans in -/home/Mame/fonts path/s
Matching font: 0x5616ad29be40
unzip: opened archive file /home/Mame/Mame_Arcade/roms/mushisam.zip
unzip: found /home/Mame/Mame_Arcade/roms/mushisam.zip ECD
unzip: /home/Mame/Mame_Arcade/roms/mushisam.zip has no ZIP64 ECD locator
unzip: read /home/Mame/Mame_Arcade/roms/mushisam.zip central directory
unzip: closing archive file /home/Mame/Mame_Arcade/roms/mushisam.zip and sending to cache
unzip: found /home/Mame/Mame_Arcade/roms/mushisam.zip in cache
unzip: opened archive file /home/Mame/Mame_Arcade/roms/mushisam.zip
unzip: closing archive file /home/Mame/Mame_Arcade/roms/mushisam.zip and sending to cache
unzip: found /home/Mame/Mame_Arcade/roms/mushisam.zip in cache
unzip: opened archive file /home/Mame/Mame_Arcade/roms/mushisam.zip
unzip: closing archive file /home/Mame/Mame_Arcade/roms/mushisam.zip and sending to cache
unzip: found /home/Mame/Mame_Arcade/roms/mushisam.zip in cache
unzip: opened archive file /home/Mame/Mame_Arcade/roms/mushisam.zip
unzip: closing archive file /home/Mame/Mame_Arcade/roms/mushisam.zip and sending to cache
:: invalid BIOS "0", reverting to default
WARNING: the machine might not run correctly.
Optional memory region ':screen' not found
Starting Mushihime-Sama (2004/10/12.MASTER VER.) ':'
  (missing dependencies; rescheduling)
Starting Hitachi SH-3 (big) ':maincpu'
Starting Epson RTC-9701-JE RTC/EEPROM ':eeprom'
Starting Serial Flash ':game'
Starting Video Screen ':screen'
[:screen] :screen: Deprecated legacy Old Style screen configured (MCFG_SCREEN_VBLANK_TIME), please use MCFG_SCREEN_RAW_PARAMS instead.
Starting palette ':palette'
Starting Speaker ':mono'
  (missing dependencies; rescheduling)
Starting Yamaha YMZ770C AMMS-A ':ymz770'
Starting EPIC12 Blitter ':blitter'
Starting Mushihime-Sama (2004/10/12.MASTER VER.) ':'
  (missing dependencies; rescheduling)
Starting Speaker ':mono'
Starting Mushihime-Sama (2004/10/12.MASTER VER.) ':'
Attempting to parse: default.cfg
Attempting to parse: mushisam.cfg
Soft reset
[:maincpu] ':maincpu' (00000006): unmapped internal write to ffffff84 = 0000a500 & 0000ffff (unk)
[:maincpu] ':maincpu' (00000006): unmapped internal write to ffffff84 = 0000a507 & 0000ffff (unk)
[:maincpu] ':maincpu' (00000006): unmapped internal write to ffffff84 = 5a000000 & ffff0000 (unk)
[:maincpu] ':maincpu' (00000006): unmapped internal write to ffffff80 = 01120000 & ffff0000 (unk)
[:maincpu] ':maincpu' (00000006): unmapped internal write to 04000010 = 80000000 & ffff0000
[:maincpu] ':maincpu' (00000006): unmapped internal write to ffffff60 = c0080000 & ffff0000 (unk)
[:maincpu] ':maincpu' (00000006): unmapped internal write to ffffff60 = 000039f0 & 0000ffff (unk)
[:maincpu] ':maincpu' (00000006): unmapped internal write to ffffff64 = 95510000 & ffff0000 (unk)
[:maincpu] ':maincpu' (00000006): unmapped internal write to ffffff64 = 0000fdd7 & 0000ffff (unk)
[:maincpu] ':maincpu' (00000006): unmapped internal write to ffffff68 = 543c0000 & ffff0000 (unk)
[:maincpu] ':maincpu' (00000006): unmapped internal write to ffffff70 = 0000a560 & 0000ffff (unk)
[:maincpu] ':maincpu' (00000006): unmapped internal write to ffffff70 = a5000000 & ffff0000 (unk)
[:maincpu] ':maincpu' (00000006): unmapped internal write to ffffff6c = 0000a510 & 0000ffff (unk)
[:maincpu] ':maincpu' (00000006): unmapped internal write to ffffe880 = 00000000 & ffff0000 (unk)
[:maincpu] ':maincpu' (00000006): unmapped internal write to 04000104 = aaaa0000 & ffff0000 (PCCR)
[:maincpu] ':maincpu' (00000006): unmapped internal write to 04000104 = 0000aaaa & 0000ffff (PDCR)
[:maincpu] ':maincpu' (00000006): unmapped internal write to 04000114 = aaaa0000 & ffff0000 (PLCR)
[:maincpu] ':maincpu' (00000006): unmapped internal write to 04000110 = a5440000 & ffff0000 (PJCR)
[:maincpu] ':maincpu' (00000006): unmapped internal write to 04000108 = 19440000 & ffff0000 (PECR)
[:maincpu] ':maincpu' (00000006): unmapped io memory write to A0 = 00000000000000FF & FFFFFFFFFFFFFFFF
[:maincpu] ':maincpu' (00000006): unmapped internal write to 04000108 = 00000009 & 0000ffff (PFCR)
[:maincpu] ':maincpu' (00000006): unmapped internal write to 0400010c = 00000000 & ffff0000 (PGCR)
[:maincpu] ':maincpu' (00000006): unmapped internal write to 0400010c = 00000000 & 0000ffff (PHCR)
[:maincpu] ':maincpu' (00000006): unmapped internal write to 04000114 = 00000000 & 0000ffff (SCPCR)
[:maincpu] sh4_rtc_timer_callback uses m_m[] with SH3
GL texture: copy 0, shader 0, dynamic 0, 320x240 320x240 [RGB32, Equal: 1, Palette: 0,
            scale 1x1, border 0, pitch 512,320/16384], bytes/pix 4
GL texture: copy 0, shader 0, dynamic 0, 320x240 320x240 [RGB32, Equal: 1, Palette: 0,
            scale 1x1, border 0, pitch 512,320/16384], bytes/pix 4
[:maincpu] ':maincpu' (00000094): INTC internal write to 04000014 = 00000430 & 0000ffff (IPRC)
[:maincpu] ':maincpu' (0c002c60): unmapped internal read from ffffffec mask ffffffff
[:maincpu] ':maincpu' (0c002c60): unmapped internal write to ffffffec = 00000008 & ffffffff (unk)
[:maincpu] ':maincpu' (000000e8): unmapped internal write to ffffffec = 00000001 & ffffffff (unk)
[:] unknown serial_rtc_eeprom_w access offset 02 data 01
[:blitter] Detected firmware version D
[:blitter] Detected firmware version D
[:blitter] Detected firmware version D
[:] unknown serial_rtc_eeprom_w access offset 02 data fe
[:maincpu] ':maincpu' (0c04eddc): TMU internal write to fffffe90 = 00000000 & 0000ff00 (SH3_TOCR_TSTR_ADDR)
[:maincpu] ':maincpu' (0c0598e6): TMU internal write to fffffe90 = 00000200 & 0000ff00 (SH3_TOCR_TSTR_ADDR)
[:maincpu] ':maincpu' (0c04ee22): INTC internal read from fffffee0 mask 0000ffff (SH3_ICR0_IPRA_ADDR - 00000000)
[:maincpu] ':maincpu' (0c04ee22): INTC internal write to fffffee0 = 00000100 & 0000ffff (SH3_ICR0_IPRA_ADDR - IPRA)
[:maincpu] setting priorities TMU0 0 TMU1 1 TMU2 0 RTC 0
[:maincpu] ':maincpu' (0c0023d4): unmapped internal read from 04000004 mask ff000000 (IRR0)
[:maincpu] ':maincpu' (0c0023d4): unmapped internal write to 04000004 = 00000000 & ff000000 (IRR0)
[:maincpu] ':maincpu' (0c000100): unmapped internal read from ffffffd4 mask ffffffff (SH3 EXPEVT - 00000160)
[:maincpu] ':maincpu' (0c002890): unmapped internal read from ffffffd0 mask ffffffff (SH3 TRA - 0000003c)
[:maincpu] ':maincpu' (0c16144c): unmapped internal read from ffffffec mask ffffffff
[:maincpu] ':maincpu' (0c16144c): unmapped internal write to ffffffec = 00000009 & ffffffff (unk)
Segmentation fault (core dumped)
```
Thanks

**Comment by angelosa** [comment]
Where's the stack trace provided with `SYMBOLS=1` at compile time, the log provided is useless.

**Comment by wwark** [comment]
I have compiled mame with SYMBOLS=1, the mamebin is now 1.4Go
I tried the new build with those settings on mame.ini.
#
# CORE DEBUGGING OPTIONS
#
verbose                   1
log                       0
oslog                     1
debug                     0
update_in_pause           0
debugscript               
debuglog                  1

The logs generated is the same without stack trace. Maybe I didn't check at the right place.

```
GL texture: copy 0, shader 0, dynamic 0, 320x240 320x240 [RGB32, Equal: 1, Palette: 0,
            scale 1x1, border 0, pitch 512,320/16384], bytes/pix 4
GL texture: copy 0, shader 0, dynamic 0, 320x240 320x240 [RGB32, Equal: 1, Palette: 0,
            scale 1x1, border 0, pitch 512,320/16384], bytes/pix 4
[:maincpu] ':maincpu' (00000010): unmapped internal write to ffffff84 = 0000a500 & 0000ffff (unk)
[:maincpu] ':maincpu' (00000014): unmapped internal write to ffffff84 = 0000a507 & 0000ffff (unk)
[:maincpu] ':maincpu' (00000018): unmapped internal write to ffffff84 = 5a000000 & ffff0000 (unk)
[:maincpu] ':maincpu' (0000001c): unmapped internal write to ffffff80 = 01120000 & ffff0000 (unk)
[:maincpu] ':maincpu' (00000022): unmapped internal write to 04000010 = 80000000 & ffff0000
[:maincpu] ':maincpu' (00000026): unmapped internal write to ffffff60 = c0080000 & ffff0000 (unk)
[:maincpu] ':maincpu' (0000002a): unmapped internal write to ffffff60 = 000039f0 & 0000ffff (unk)
[:maincpu] ':maincpu' (0000002e): unmapped internal write to ffffff64 = 95510000 & ffff0000 (unk)
[:maincpu] ':maincpu' (00000032): unmapped internal write to ffffff64 = 0000fdd7 & 0000ffff (unk)
[:maincpu] ':maincpu' (00000036): unmapped internal write to ffffff68 = 543c0000 & ffff0000 (unk)
[:maincpu] ':maincpu' (0000003a): unmapped internal write to ffffff70 = 0000a560 & 0000ffff (unk)
[:maincpu] ':maincpu' (0000003e): unmapped internal write to ffffff70 = a5000000 & ffff0000 (unk)
[:maincpu] ':maincpu' (00000042): unmapped internal write to ffffff6c = 0000a510 & 0000ffff (unk)
[:maincpu] ':maincpu' (00000048): unmapped internal write to ffffe880 = 00000000 & ffff0000 (unk)
[:maincpu] ':maincpu' (0000004e): unmapped internal write to 04000104 = aaaa0000 & ffff0000 (PCCR)
[:maincpu] ':maincpu' (00000050): unmapped internal write to 04000104 = 0000aaaa & 0000ffff (PDCR)
[:maincpu] ':maincpu' (00000052): unmapped internal write to 04000114 = aaaa0000 & ffff0000 (PLCR)
[:maincpu] ':maincpu' (00000058): unmapped internal write to 04000110 = a5440000 & ffff0000 (PJCR)
[:maincpu] ':maincpu' (0000005e): unmapped internal write to 04000108 = 19440000 & ffff0000 (PECR)
[:maincpu] ':maincpu' (00000066): unmapped io memory write to A0 = 00000000000000FF & FFFFFFFFFFFFFFFF
[:maincpu] ':maincpu' (0000006c): unmapped internal write to 04000108 = 00000009 & 0000ffff (PFCR)
[:maincpu] ':maincpu' (00000072): unmapped internal write to 0400010c = 00000000 & ffff0000 (PGCR)
[:maincpu] ':maincpu' (00000078): unmapped internal write to 0400010c = 00000000 & 0000ffff (PHCR)
[:maincpu] ':maincpu' (0000007e): unmapped internal write to 04000114 = 00000000 & 0000ffff (SCPCR)
[:maincpu] sh4_rtc_timer_callback uses m_m[] with SH3
[:maincpu] ':maincpu' (000000d8): INTC internal write to 04000014 = 00000430 & 0000ffff (IPRC)
[:maincpu] ':maincpu' (0c002c78): unmapped internal read from ffffffec mask ffffffff
[:maincpu] ':maincpu' (0c002c7c): unmapped internal write to ffffffec = 00000008 & ffffffff (unk)
[:maincpu] ':maincpu' (000000ea): unmapped internal write to ffffffec = 00000001 & ffffffff (unk)
[:] unknown serial_rtc_eeprom_w access offset 02 data 01
[:blitter] Detected firmware version D
[:blitter] Detected firmware version D
[:blitter] Detected firmware version D
[:] unknown serial_rtc_eeprom_w access offset 02 data fe
[:maincpu] ':maincpu' (0c04edee): TMU internal write to fffffe90 = 00000000 & 0000ff00 (SH3_TOCR_TSTR_ADDR)
[:maincpu] ':maincpu' (0c04ee20): TMU internal write to fffffe90 = 00000200 & 0000ff00 (SH3_TOCR_TSTR_ADDR)
[:maincpu] ':maincpu' (0c04ee28): INTC internal read from fffffee0 mask 0000ffff (SH3_ICR0_IPRA_ADDR - 00000000)
[:maincpu] ':maincpu' (0c04ee2e): INTC internal write to fffffee0 = 00000100 & 0000ffff (SH3_ICR0_IPRA_ADDR - IPRA)
[:maincpu] setting priorities TMU0 0 TMU1 1 TMU2 0 RTC 0
[:maincpu] ':maincpu' (0c002412): unmapped internal read from 04000004 mask ff000000 (IRR0)
[:maincpu] ':maincpu' (0c002416): unmapped internal write to 04000004 = 00000000 & ff000000 (IRR0)
[:maincpu] ':maincpu' (0c000104): unmapped internal read from ffffffd4 mask ffffffff (SH3 EXPEVT - 00000160)
[:maincpu] ':maincpu' (0c0028be): unmapped internal read from ffffffd0 mask ffffffff (SH3 TRA - 0000003c)
[:maincpu] ':maincpu' (0c16145a): unmapped internal read from ffffffec mask ffffffff
[:maincpu] ':maincpu' (0c16145e): unmapped internal write to ffffffec = 00000009 & ffffffff (unk)
Segmentation fault (core dumped)
```

Thanks for your help !

**Comment by wwark** [comment]
Thank you for your return.

**Last logs of run:**
[:] unknown serial_rtc_eeprom_w access offset 02 data 01
[:blitter] Detected firmware version D
[:blitter] Detected firmware version D
[:blitter] Detected firmware version D
[:] unknown serial_rtc_eeprom_w access offset 02 data fe
[:maincpu] ':maincpu' (0c04edee): TMU internal write to fffffe90 = 00000000 & 0000ff00 (SH3_TOCR_TSTR_ADDR)
[:maincpu] ':maincpu' (0c04ee20): TMU internal write to fffffe90 = 00000200 & 0000ff00 (SH3_TOCR_TSTR_ADDR)
[:maincpu] ':maincpu' (0c04ee28): INTC internal read from fffffee0 mask 0000ffff (SH3_ICR0_IPRA_ADDR - 00000000)
[:maincpu] ':maincpu' (0c04ee2e): INTC internal write to fffffee0 = 00000100 & 0000ffff (SH3_ICR0_IPRA_ADDR - IPRA)
[:maincpu] setting priorities TMU0 0 TMU1 1 TMU2 0 RTC 0
[:maincpu] ':maincpu' (0c002412): unmapped internal read from 04000004 mask ff000000 (IRR0)
[:maincpu] ':maincpu' (0c002416): unmapped internal write to 04000004 = 00000000 & ff000000 (IRR0)
[:maincpu] ':maincpu' (0c000104): unmapped internal read from ffffffd4 mask ffffffff (SH3 EXPEVT - 00000160)
[:maincpu] ':maincpu' (0c0028be): unmapped internal read from ffffffd0 mask ffffffff (SH3 TRA - 0000003c)
[:maincpu] ':maincpu' (0c16145a): unmapped internal read from ffffffec mask ffffffff
[:maincpu] ':maincpu' (0c16145e): unmapped internal write to ffffffec = 00000009 & ffffffff (unk)

Thread 1 "mamebin" received signal SIGSEGV, Segmentation fault.
0x0000555560876604 in sh34_base_device::sh4_exception () at ../../../../../src/devices/cpu/sh/sh4comn.cpp:412
412				standard_irq_callback(INPUT_LINE_NMI);

**(gdb) bt full**
#0  0x0000555560876604 in sh34_base_device::sh4_exception(char const*, int) () at ../../../../../src/devices/cpu/sh/sh4comn.cpp:412
#1  0x000055556085df84 in sh34_base_device::sh4_check_pending_irq(char const*) () at ../../../../../src/devices/cpu/sh/sh4.h:409
#2  sh34_base_device::func_CHECKIRQ() () at ../../../../../src/devices/cpu/sh/sh4.cpp:2620
#3  cfunc_CHECKIRQ() () at ../../../../../src/devices/cpu/sh/sh4.cpp:2621
#4  0x00007ffff132f11d in  ()
#5  0x0000000000004421 in  ()
#6  0x00007fffffff7c00 in  ()
#7  0x0000555561eafc3d in operator() () at ../../../../../src/devices/cpu/drcbex64.cpp:653
#8  _FUN() () at ../../../../../src/devices/cpu/drcbex64.cpp:653
#9  0x0c04f10c8c000000 in  ()
#10 0x0c04f10c00000000 in  ()
#11 0x0c422a2040000001 in  ()
#12 0x0c267f3c00000004 in  ()
#13 0x0000008000000840 in  ()
#14 0x0000000000000001 in  ()
#15 0x000001600c267f3c in  ()
#16 0x0c246a880c002890 in  ()
#17 0x0000000100000000 in  ()
#18 0x0c246a700c246a74 in  ()
#19 0x0c7fffa00c04a2bc in  ()
#20 0x0000000000000000 in  ()

**Comment by angelosa** [comment]
Does it happens without drc? Call to NMI is weird, I don't think neither cv1k nor sh3 should really call it at all.
`gdb --args ./mame mushisam -nodrc`

**Comment by wwark** [comment]
it works with the option -nodrc

**Comment by firewave** [comment]
It very much looks like a NULL reference. Running it in `valgrind` should expose the usage of the bad pointer - `valgrind ./mame mushisam -nodrc`.

**Comment by wwark** [comment]
with valgrind and -nodrc option the game starts without issue it is just long.

Below the vagrind command without -nodrc parameter

```
[:maincpu] ':maincpu' (0c0023d4): unmapped internal read from 04000004 mask ff000000 (IRR0)
[:maincpu] ':maincpu' (0c0023d4): unmapped internal write to 04000004 = 00000000 & ff000000 (IRR0)
[:maincpu] ':maincpu' (0c000100): unmapped internal read from ffffffd4 mask ffffffff (SH3 EXPEVT - 00000160)
[:maincpu] ':maincpu' (0c002890): unmapped internal read from ffffffd0 mask ffffffff (SH3 TRA - 0000003c)
[:maincpu] ':maincpu' (0c16144c): unmapped internal read from ffffffec mask ffffffff
[:maincpu] ':maincpu' (0c16144c): unmapped internal write to ffffffec = 00000009 & ffffffff (unk)
==2012774== 
==2012774== Process terminating with default action of signal 11 (SIGSEGV)
==2012774==  General Protection Fault
==2012774==    at 0xB42A494: sh34_base_device::sh4_exception(char const*, int) (sh4comn.cpp:412)
==2012774==    by 0xB411E13: sh4_check_pending_irq (sh4.h:409)
==2012774==    by 0xB411E13: func_CHECKIRQ (sh4.cpp:2620)
==2012774==    by 0xB411E13: cfunc_CHECKIRQ(void*) (sh4.cpp:2621)
==2012774==    by 0x1D959110: ???
==2012774==    by 0xB412916: RTE (sh4.cpp:476)
==2012774==    by 0xB412916: func_RTE (sh4.cpp:3012)
==2012774==    by 0xB412916: cfunc_RTE(void*) (sh4.cpp:3013)
==2012774==    by 0x1BB981AF: ???
==2012774==    by 0x1BB981AF: ???
==2012774==    by 0x1D87907F: ???
==2012774==    by 0x1DDC4F43: ???
==2012774==    by 0x1DDC55A3: ???
==2012774==    by 0xDDEDB4E: apply_sample_rate_changes (sound.cpp:543)
==2012774==    by 0xDDEDB4E: apply_sample_rate_changes (sound.cpp:532)
==2012774==    by 0xDDEDB4E: sound_stream::apply_sample_rate_changes(unsigned int, unsigned int) (sound.cpp:813)
==2012774==    by 0x4ECA9BEF: ???
==2012774==    by 0x1B4B3A6F: ???
==2012774== 
==2012774== HEAP SUMMARY:
==2012774==     in use at exit: 388,233,076 bytes in 228,902 blocks
==2012774==   total heap usage: 17,090,823 allocs, 16,861,921 frees, 7,276,723,332 bytes allocated
==2012774== 
==2012774== LEAK SUMMARY:
==2012774==    definitely lost: 4,960 bytes in 4 blocks
==2012774==    indirectly lost: 87,224 bytes in 25 blocks
==2012774==      possibly lost: 2,584,699 bytes in 22,939 blocks
==2012774==    still reachable: 385,556,193 bytes in 205,934 blocks
==2012774==                       of which reachable via heuristic:
==2012774==                         newarray           : 65,552 bytes in 2 blocks
==2012774==         suppressed: 0 bytes in 0 blocks
==2012774== Rerun with --leak-check=full to see details of leaked memory
==2012774== 
==2012774== Use --track-origins=yes to see where uninitialised values come from
==2012774== For lists of detected and suppressed errors, rerun with: -s
==2012774== ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)
```

**Comment by angelosa** [comment]
Yeah, it's definitely calling a SH4 NMI while being a SH3[BE].
https://github.com/mamedev/mame/blob/efbb20204ba7c60141598390b3ff9413be0064f3/src/mame/misc/cv1k.cpp#L234
I wonder if casting this to actual `sh3be_device` fixes the issue.

**Comment by wwark** [comment]
Yes I have an Intel CPU.
I will compile with the options provided let you know !
Thanks for your time

**Comment by firewave** [comment]
No issues reported with ASAN or UBSAN on Ubuntu 20.04 with 0.249 compiled with Clang 14 with DRC on or off. I only played like a minute though.

**Comment by Kaede573** [comment]
Hello,  
  
I am running into the same issue - immediate crash (using mushisam) unless I use -nodrc.
MAME 0.251 compiled from sources using gcc. I have used "make -j17 SYMBOLS=1 ARCHOPTS_C=-mcmodel=large ARCHOPTS_CXX=-mcmodel=large REGENIE=1" for compiling (tried "make -j17" before finding this github report, then I gave a try at these options feedback was being asked for).  
CPU: i5-12600KF.  
gcc: gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0  
  
I ran it with gdb / ran bt full also, however the info seems 99% identical to what was posted for 0.249, so I would rather not clutter the thread and post it, please let me know if it's useful anyway.

**Comment by angelosa** [comment]
Duplicate of #9186
