### ISSUE TITLE
New issue, regression from .251, HLSL and Game & Watch combo causing failure to display and then AVs:

### ISSUE THREAD

**Issue by john-iv** [mamedev/mame#10872]
New issue, regression from .251, HLSL and Game & Watch combo causing failure to display and then AVs:
`mame -v gnw_bjack -video d3d -hlsl_enable -norc`

0.251 (mame0251-342-g678eb8d5cf2)
Windows 11 x64 22H2 22621.1194
AMD 5600XT
Raster.ini and gnw_bjack artwork attached

```
Attempting to parse: default.cfg
Attempting to parse: gnw_bjack.cfg
Direct3D: Get texture target - not found - 960x645:0
Direct3D: Create texture target - 536x368
Direct3D: Get texture target - not found - 960x645:1
Direct3D: Create texture target - 536x368
Direct3D: Get texture target - not found - 960x648:2
Direct3D: Create texture target - 529x355
Direct3D: Get texture target - not found - 960x648:3
Direct3D: Create texture target - 530x356
-----------------------------------------------------
Exception at EIP=00007ff70c2d5dd9 (not found): ACCESS VIOLATION
While attempting to read memory at 00000000000004e8
-----------------------------------------------------
RAX=0000000000000000 RBX=000001b200ccb850 RCX=00007ff715cd02b0 RDX=00007ff715cd02b0
RSI=0000000000000000 RDI=0000000000000001 RBP=00007ff715cd02b0 RSP=000000790fbf8a40
 R8=0000000000000000  R9=fffffffffff2cae0 R10=b1d1877f545bc370 R11=8101010101010100
R12=000001b200ce3110 R13=0000000000000000 R14=000001b21beb8e40 R15=000001b215ed57e0
-----------------------------------------------------
Stack crawl:
  000000790fbf8ab0: 00007ff70c2d5dd9 (not found)
  000000790fbf8b90: 00007ff70c2dbaa8 (not found)
  000000790fbf8d10: 00007ff70c21a40d (not found)
  000000790fbf8dc0: 00007ff70c21a678 (not found)
  000000790fbf8e20: 00007ff70c220221 (not found)
  000000790fbf8e80: 00007ff70c2345e8 (not found)
  000000790fbf8f70: 00007ff70c236385 (not found)
  000000790fbf90d0: 00007ff9e51b8281 (DispatchMessageW+0x0741)
  000000790fbf9120: 00007ff9e51b7acb (CallWindowProcW+0x008b)
  000000790fbf91c0: 00007ff97ae3a8fe (Direct3DCreate9Ex+0x4a3e)
  000000790fbf9320: 00007ff9e51b8281 (DispatchMessageW+0x0741)
  000000790fbf93d0: 00007ff9e51b77ad (SendMessageW+0x037d)
  000000790fbf9430: 00007ff9e51b7567 (SendMessageW+0x0137)
  000000790fbf9470: 00007ff70c23339a (not found)
  000000790fbf9500: 00007ff70c1b16f0 (not found)
  000000790fbf9560: 00007ff70c168e9a (not found)
  000000790fbf95d0: 00007ff70c16350b (not found)
  000000790fbf9750: 00007ff70c1116d0 (not found)
  000000790fbfebe0: 00007ff70cb9c746 (not found)
  000000790fbfefd0: 00007ff70cc37fd6 (not found)
  000000790fbff2e0: 00007ff70cc385ea (not found)
  000000790fbff340: 00007ff70cb96f97 (not found)
  000000790fbff700: 00007ff711ef7970 (not found)
  000000790fbff750: 00007ff7056c12ee (not found)
  000000790fbff780: 00007ff7056c1406 (not found)
  000000790fbff7b0: 00007ff9e54126bd (BaseThreadInitThunk+0x001d)
  000000790fbff830: 00007ff9e698dfb8 (RtlUserThreadStart+0x0028)`
```
[raster.zip](https://github.com/mamedev/mame/files/10611811/raster.zip)
[gnw_bjack.zip](https://github.com/mamedev/mame/files/10611865/gnw_bjack.zip)

_Originally posted by @john-iv in https://github.com/mamedev/mame/issues/10859#issuecomment-1418207888_

**Comment by Robbbert** [comment]
This is working for me. Is it still an issue?

**Comment by john-iv** [comment]
Yes, on two machines with `0.252 (mame0252-61-g7c29401312b)`

I have D3D9 on both.  The only alteration from a default MAME tree is I have my handheld artwork in a separate directory so the gnw_bjack is in 'artwork_handheld'.

`mame -v gnw_bjack -video d3d -hlsl_enable -norc -artpath artwork_handheld`

[D3D Error.txt](https://github.com/mamedev/mame/files/10820157/D3D.Error.txt)

**Comment by cuavas** [comment]
It only happens with that artwork, it doesn’t happen with the built-in layout.

Stack trace:
```
#0  0x00007ff636c3b49c in shaders::scanline_pass(d3d_render_target*, int, poly_info*, int) ()
#1  0x00007ff636c3cbab in shaders::render_quad(poly_info*, int) ()
#2  0x00007ff636346be3 in renderer_d3d9::primitive_flush_pending() ()
#3  0x00007ff636347104 in renderer_d3d9::end_frame() ()
#4  0x00007ff63634ca0d in renderer_d3d9::draw(int) ()
#5  0x00007ff632bfe62b in win_window_info::draw_video_contents(HDC__*, bool) ()
#6  0x00007ff632c00509 in win_window_info::video_window_proc(HWND__*, unsigned int, unsigned long long, long long) ()
#7  0x00007ff80bfce858 in USER32!CallWindowProcW () from C:\WINDOWS\System32\user32.dll
#8  0x00007ff80bfcde1b in USER32!SendMessageW () from C:\WINDOWS\System32\user32.dll
#9  0x00007ff80bfcd68a in USER32!SendMessageW () from C:\WINDOWS\System32\user32.dll
#10 0x00007ff632c0ab2a in windows_osd_interface::update(bool) ()
#11 0x00007ff632dcef21 in video_manager::frame_update(bool) ()
#12 0x00007ff62f0590a2 in screen_device::vblank_begin(int) ()
#13 0x00007ff62f0452af in device_scheduler::timeslice() ()
#14 0x00007ff62f041388 in running_machine::run(bool) ()
#15 0x00007ff632be3fbb in mame_machine_manager::execute() ()
#16 0x00007ff63629d9ff in cli_frontend::start_execution(mame_machine_manager*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) ()
#17 0x00007ff63629e00d in cli_frontend::execute(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) ()
#18 0x00007ff632bdebd9 in emulator_info::start_frontend(emu_options&, osd_interface&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) ()
#19 0x00007ff6375ffa29 in main ()
```

It seems to be crashing trying to get the render container for the screen in `shaders::scanline_pass` (in src/osd/modules/render/d3d/d3dhlsl.cpp).
