### ISSUE TITLE
macqd950 fail to boot (segmentation fault)

### ISSUE THREAD

**Issue by cd4053** [mamedev/mame#13100]
### MAME version

0.272 (mame0272-322-g7a755b7d73f)

### System information

Debian 12 x64

### Emulated system/software

Macintosh Quadra 950

### Incorrect behaviour

Emulation ends with Segmentation fault.

GDB:

```
Thread 1 "mamed" received signal SIGSEGV, Segmentation fault.
0x000055555f9d3162 in emu_timer::adjust(attotime, int, attotime const&) () at ../../../../../src/emu/schedule.cpp:139
warning: Source file is more recent than executable.
139		assert(m_scheduler);
─── Assembly ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 0x000055555f9d3162  ? cmpq   $0x0,(%rax)
 0x000055555f9d3166  ? je     0x55555f9d316a <_ZN9emu_timer6adjustE8attotimeiRKS0_+298>
 0x000055555f9d3168  ? jmp    0x55555f9d318e <_ZN9emu_timer6adjustE8attotimeiRKS0_+334>
 0x000055555f9d316a  ? call   0x555557ec1ac0 <__asan_handle_no_return>
 0x000055555f9d316f  ? lea    -0x905d956(%rip),%rdi        # 0x555556975820 <.str>
 0x000055555f9d3176  ? lea    -0x905d93d(%rip),%rsi        # 0x555556975840 <.str.1>
 0x000055555f9d317d  ? mov    $0x8b,%edx
 0x000055555f9d3182  ? lea    -0x905d8a9(%rip),%rcx        # 0x5555569758e0 <__PRETTY_FUNCTION__._ZN9emu_timer6adjustE8attotimeiRKS0_>
 0x000055555f9d3189  ? call   0x5555614315e0 <__assert_fail@plt>
 0x000055555f9d318e  ? mov    0x78(%rbx),%rax
─── Breakpoints ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
─── Expressions ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
─── History ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
─── Memory ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
─── Registers ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    rax 0x0000000000000000     rbx 0x00007fffffffc960     rcx 0xf2f2f8f8f1f1f1f1     rdx 0x0000000000000000         rsi 0xffffffffffffffff         rdi 0x0000000000000000     rbp 0x00007fffffffca50        rsp 0x00007fffffffc960     r8 0x00007fffffffff01     r9 0x0000000000001f01
    r10 0x00000ffffc93e801     r11 0x0000000000000000     r12 0x0000000000000000     r13 0x00007fffffffdba0         r14 0x00007ffff7ffd000         r15 0x0000555561436a40     rip 0x000055555f9d3162     eflags [ PF ZF IF RF ID ]     cs 0x00000033             ss 0x0000002b        
     ds 0x00000000              es 0x00000000              fs 0x00000000              gs 0x00000000             fs_base 0x00007fffe89750c0     gs_base 0x0000000000000000
─── Source ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 134  //  firings
 135  //-------------------------------------------------
 136  
 137  void emu_timer::adjust(attotime start_delay, s32 param, const attotime &period) noexcept
 138  {
 139      assert(m_scheduler);
 140  
 141      // if this is the callback timer, mark it modified
 142      if (m_scheduler->m_callback_timer == this)
 143          m_scheduler->m_callback_timer_modified = true;
─── Stack ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[0] from 0x000055555f9d3162 in emu_timer::adjust(attotime, int, attotime const&) at ../../../../../src/emu/schedule.cpp:139
[1] from 0x0000555557f12173 in (anonymous namespace)::quadrax00_state::machine_reset() at ../../../../../src/mame/apple/macquadra700.cpp:312
[2] from 0x0000555557f13058 in (anonymous namespace)::eclipse_state::machine_reset() at ../../../../../src/mame/apple/macquadra700.cpp:326
[3] from 0x000055555b9a3c72 in driver_device::device_reset_after_children() at ../../../../../src/emu/driver.cpp:248
[4] from 0x000055555b85d97a in device_t::reset() at ../../../../../src/emu/device.cpp:351
[5] from 0x000055555f7390f6 in running_machine::reset_all_devices() at ../../../../../src/emu/machine.cpp:1040
[6] from 0x00005555591b7ac6 in util::detail::delegate_base<delegate_late_bind, void>::operator()() const at ../../../../../src/lib/util/delegate.h:765
[7] from 0x000055555f73da8b in running_machine::call_notifiers(machine_notification) at ../../../../../src/emu/machine.cpp:851
[8] from 0x000055555f738c6e in running_machine::soft_reset(int) at ../../../../../src/emu/machine.cpp:956
[9] from 0x000055555f73a940 in running_machine::run(bool) at ../../../../../src/emu/machine.cpp:313
[+]
─── Threads ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[15] id 151060 name SDLAudioP1 from 0x00007ffff5e9891e in __futex_abstimed_wait_common64+127 at ./nptl/futex-internal.c:57
[13] id 151058 name PulseMainloop from 0x00007ffff5f0ce9f in __GI___poll+79 at ../sysdeps/unix/sysv/linux/poll.c:29
[12] id 151057 name mamed:sh1 from 0x00007ffff5e9891e in __futex_abstimed_wait_common64+127 at ./nptl/futex-internal.c:57
[10] id 151054 name mamed:gdrv0 from 0x00007ffff5e9891e in __futex_abstimed_wait_common64+127 at ./nptl/futex-internal.c:57
[11] id 151055 name mamed:gl0 from 0x00007ffff5e9891e in __futex_abstimed_wait_common64+127 at ./nptl/futex-internal.c:57
[8] id 151052 name mamed:traceq0 from 0x00007ffff5e9891e in __futex_abstimed_wait_common64+127 at ./nptl/futex-internal.c:57
[7] id 151051 name mamed:traceq0 from 0x00007ffff5e9891e in __futex_abstimed_wait_common64+127 at ./nptl/futex-internal.c:57
[6] id 151050 name mamed:sh_opt0 from 0x00007ffff5e9891e in __futex_abstimed_wait_common64+127 at ./nptl/futex-internal.c:57
[4] id 151048 name mamed:disk$0 from 0x00007ffff5e9891e in __futex_abstimed_wait_common64+127 at ./nptl/futex-internal.c:57
[9] id 151053 name mamed:traceq0 from 0x00007ffff5e9891e in __futex_abstimed_wait_common64+127 at ./nptl/futex-internal.c:57
[3] id 151047 name mamed:rcs0 from 0x00007ffff5e9891e in __futex_abstimed_wait_common64+127 at ./nptl/futex-internal.c:57
[14] id 151059 name PulseHotplug from 0x00007ffff5e9891e in __futex_abstimed_wait_common64+127 at ./nptl/futex-internal.c:57
[5] id 151049 name mamed:sh0 from 0x00007ffff5e9891e in __futex_abstimed_wait_common64+127 at ./nptl/futex-internal.c:57
[2] id 151039 name mamed from 0x00007ffff5e9891e in __futex_abstimed_wait_common64+127 at ./nptl/futex-internal.c:57
[1] id 151035 name mamed from 0x000055555f9d3162 in emu_timer::adjust(attotime, int, attotime const&) at ../../../../../src/emu/schedule.cpp:139
```

AddressSanitizer:

```AddressSanitizer:DEADLYSIGNAL
=================================================================
==151266==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x564841840162 bp 0x7ffced84f290 sp 0x7ffced84f1a0 T0)
==151266==The signal is caused by a READ memory access.
==151266==Hint: address points to the zero page.
    #0 0x564841840162 in emu_timer::adjust(attotime, int, attotime const&) /home/mame/build/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/emu/schedule.cpp:139:2
    #1 0x564839d7f172 in (anonymous namespace)::quadrax00_state::machine_reset() /home/mame/build/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/mame/apple/macquadra700.cpp:312:16
    #2 0x564839d80057 in (anonymous namespace)::eclipse_state::machine_reset() /home/mame/build/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/mame/apple/macquadra700.cpp:326:19
    #3 0x56483d810c71 in driver_device::device_reset_after_children() /home/mame/build/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/emu/driver.cpp:248:3
    #4 0x56483d6ca979 in device_t::reset() /home/mame/build/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/emu/device.cpp:351:2
    #5 0x5648415a60f5 in running_machine::reset_all_devices() /home/mame/build/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/emu/machine.cpp:1040:16
    #6 0x56483b024ac5 in util::detail::delegate_base<delegate_late_bind, void>::operator()() const /home/mame/build/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/lib/util/delegate.h:765:11
    #7 0x5648415aaa8a in running_machine::call_notifiers(machine_notification) /home/mame/build/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/emu/machine.cpp:851:3
    #8 0x5648415a5c6d in running_machine::soft_reset(int) /home/mame/build/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/emu/machine.cpp:956:2
    #9 0x5648415a793f in running_machine::run(bool) /home/mame/build/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/emu/machine.cpp:313:3
    #10 0x56483b0fe149 in mame_machine_manager::execute() /home/mame/build/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/frontend/mame/mame.cpp:288:19
    #11 0x56483d2f0569 in cli_frontend::start_execution(mame_machine_manager*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>> const&) /home/mame/build/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/frontend/mame/clifront.cpp:277:22
    #12 0x56483d2f2cd6 in cli_frontend::execute(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>>&) /home/mame/build/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/frontend/mame/clifront.cpp:293:3
    #13 0x56483b100936 in emulator_info::start_frontend(emu_options&, osd_interface&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>>>&) /home/mame/build/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/frontend/mame/mame.cpp:453:18
    #14 0x564841a72e0c in main /home/mame/build/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/osd/sdl/sdlmain.cpp:100:9
    #15 0x7f5ddde2cd67 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #16 0x7f5ddde2ce24 in __libc_start_main csu/../csu/libc-start.c:360:3
    #17 0x564839c840a0 in _start (/home/mame/mamed+0x28c30a0) (BuildId: 900b8dff1b1c0dfe43ebcdd66664a928fe2a2a11)

==151266==Register values:
rax = 0x0000000000000000  rbx = 0x00007ffced84f1a0  rcx = 0xf2f2f8f8f1f1f1f1  rdx = 0x0000000000000000  
rdi = 0x0000000000000000  rsi = 0xffffffffffffffff  rbp = 0x00007ffced84f290  rsp = 0x00007ffced84f1a0  
 r8 = 0x00007fffffffff01   r9 = 0x0000000000001f01  r10 = 0x00000febb993cd01  r11 = 0x0000000000000000  
r12 = 0x0000000000000000  r13 = 0x00007ffced8503e0  r14 = 0x00007f5de0010000  r15 = 0x00005648432a3a40  
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/mame/build/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/emu/schedule.cpp:139:2 in emu_timer::adjust(attotime, int, attotime const&)
==151266==ABORTING
```

### Expected behaviour

To boot.

### Steps to reproduce

Start mame with: `./mame -norc -rompath roms;/mnt/EDE5A718AF0104D9/Mame/roms macqd950`

Crash happens soon after pressing Enter to confirm.

**Comment by Robbbert** [comment]
Crash confirmed.

**Comment by Robbbert** [comment]
Also happens with the other machines in the driver: macqd700, macqd900.

**Comment by rb6502** [comment]
Fixed in https://github.com/mamedev/mame/commit/37a1ed2c29a6d4c546762a707ccfe9a9389ce8c2
