### ISSUE TITLE
Memory leak at different objects

### ISSUE THREAD

**Issue by katananja** [mamedev/mame#3023]
Debian 9 x64
Clang 3.9.1
mame0193-321-gf4f8d79998-dirty

Compiled command:
`make VERBOSE=1 OVERRIDE_CC=/usr/bin/clang-3.9 OVERRIDE_CXX=/usr/bin/clang++-3.9 REGENIE=1 SANITIZE=1 SUBTARGET=tiny SYMLEVEL=2 ARCHOPTS="-fsanitize=address" -j8`

Run as:
`ASAN_OPTIONS=strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1:symbolize=1 ./mametiny64`

```
==5972==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 8192 byte(s) in 2 object(s) allocated from:
    #0 0x531da8 in __interceptor_malloc (/mame/mame0193-321-gf4f8d79998-dirty-tiny+0x531da8)
    #1 0x7f70e4da4bef  (<unknown module>)

Direct leak of 183 byte(s) in 10 object(s) allocated from:
    #0 0x531da8 in __interceptor_malloc (/mame/mame0193-321-gf4f8d79998-dirty-tiny+0x531da8)
    #1 0x1d2bc21 in core_strdup(char const*) /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/lib/util/corestr.cpp:130:17
    #2 0x8711ec in plugin_options::parse_json(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/frontend/mame/pluginopts.cpp:78:46
    #3 0x86fa0a in plugin_options::parse_json(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/frontend/mame/pluginopts.cpp:89:6
    #4 0x8650d2 in mame_machine_manager::start_luaengine() /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/frontend/mame/mame.cpp:121:15
    #5 0x9a9a25 in cli_frontend::start_execution(mame_machine_manager*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/frontend/mame/clifront.cpp:243:11
    #6 0x9ac2a0 in cli_frontend::execute(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/frontend/mame/clifront.cpp:273:3
    #7 0x869e66 in emulator_info::start_frontend(emu_options&, osd_interface&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/frontend/mame/mame.cpp:336:18
    #8 0x672f02 in main /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/sdl/sdlmain.cpp:216:9
    #9 0x7f711a0f32b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

Direct leak of 72 byte(s) in 1 object(s) allocated from:
    #0 0x531fa0 in calloc (/mame/mame0193-321-gf4f8d79998-dirty-tiny+0x531fa0)
    #1 0x7f711b3a5a80 in XkbGetMap (/usr/lib/x86_64-linux-gnu/libX11.so.6+0x92a80)

Direct leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x531da8 in __interceptor_malloc (/mame/mame0193-321-gf4f8d79998-dirty-tiny+0x531da8)
    #1 0x1d2bc21 in core_strdup(char const*) /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/lib/util/corestr.cpp:130:17
    #2 0x69d9c1 in osd_common_t::update_option(char const*, std::vector<char const*, std::allocator<char const*> >&) const /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/modules/lib/osdobj_common.cpp:374:33
    #3 0x69cafa in osd_common_t::register_options() /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/modules/lib/osdobj_common.cpp:354:2
    #4 0x672ef4 in main /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/sdl/sdlmain.cpp:215:7
    #5 0x7f711a0f32b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

Direct leak of 46 byte(s) in 1 object(s) allocated from:
    #0 0x531da8 in __interceptor_malloc (/mame/mame0193-321-gf4f8d79998-dirty-tiny+0x531da8)
    #1 0x1d2bc21 in core_strdup(char const*) /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/lib/util/corestr.cpp:130:17
    #2 0x69d9c1 in osd_common_t::update_option(char const*, std::vector<char const*, std::allocator<char const*> >&) const /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/modules/lib/osdobj_common.cpp:374:33
    #3 0x69ca74 in osd_common_t::register_options() /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/modules/lib/osdobj_common.cpp:349:2
    #4 0x672ef4 in main /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/sdl/sdlmain.cpp:215:7
    #5 0x7f711a0f32b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

Direct leak of 44 byte(s) in 1 object(s) allocated from:
    #0 0x531da8 in __interceptor_malloc (/mame/mame0193-321-gf4f8d79998-dirty-tiny+0x531da8)
    #1 0x1d2bc21 in core_strdup(char const*) /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/lib/util/corestr.cpp:130:17
    #2 0x69d9c1 in osd_common_t::update_option(char const*, std::vector<char const*, std::allocator<char const*> >&) const /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/modules/lib/osdobj_common.cpp:374:33
    #3 0x69c4f0 in osd_common_t::register_options() /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/modules/lib/osdobj_common.cpp:327:2
    #4 0x672ef4 in main /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/sdl/sdlmain.cpp:215:7
    #5 0x7f711a0f32b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

Direct leak of 41 byte(s) in 1 object(s) allocated from:
    #0 0x531da8 in __interceptor_malloc (/mame/mame0193-321-gf4f8d79998-dirty-tiny+0x531da8)
    #1 0x1d2bc21 in core_strdup(char const*) /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/lib/util/corestr.cpp:130:17
    #2 0x69d9c1 in osd_common_t::update_option(char const*, std::vector<char const*, std::allocator<char const*> >&) const /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/modules/lib/osdobj_common.cpp:374:33
    #3 0x69c237 in osd_common_t::register_options() /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/modules/lib/osdobj_common.cpp:321:2
    #4 0x672ef4 in main /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/sdl/sdlmain.cpp:215:7
    #5 0x7f711a0f32b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

Direct leak of 41 byte(s) in 1 object(s) allocated from:
    #0 0x531da8 in __interceptor_malloc (/mame/mame0193-321-gf4f8d79998-dirty-tiny+0x531da8)
    #1 0x1d2bc21 in core_strdup(char const*) /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/lib/util/corestr.cpp:130:17
    #2 0x69d9c1 in osd_common_t::update_option(char const*, std::vector<char const*, std::allocator<char const*> >&) const /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/modules/lib/osdobj_common.cpp:374:33
    #3 0x69b9f0 in osd_common_t::register_options() /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/modules/lib/osdobj_common.cpp:303:2
    #4 0x672ef4 in main /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/sdl/sdlmain.cpp:215:7
    #5 0x7f711a0f32b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

Direct leak of 38 byte(s) in 1 object(s) allocated from:
    #0 0x531da8 in __interceptor_malloc (/mame/mame0193-321-gf4f8d79998-dirty-tiny+0x531da8)
    #1 0x1d2bc21 in core_strdup(char const*) /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/lib/util/corestr.cpp:130:17
    #2 0x69d9c1 in osd_common_t::update_option(char const*, std::vector<char const*, std::allocator<char const*> >&) const /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/modules/lib/osdobj_common.cpp:374:33
    #3 0x69bcb0 in osd_common_t::register_options() /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/modules/lib/osdobj_common.cpp:309:2
    #4 0x672ef4 in main /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/sdl/sdlmain.cpp:215:7
    #5 0x7f711a0f32b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

Direct leak of 34 byte(s) in 1 object(s) allocated from:
    #0 0x531da8 in __interceptor_malloc (/mame/mame0193-321-gf4f8d79998-dirty-tiny+0x531da8)
    #1 0x1d2bc21 in core_strdup(char const*) /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/lib/util/corestr.cpp:130:17
    #2 0x69d9c1 in osd_common_t::update_option(char const*, std::vector<char const*, std::allocator<char const*> >&) const /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/modules/lib/osdobj_common.cpp:374:33
    #3 0x69bf70 in osd_common_t::register_options() /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/modules/lib/osdobj_common.cpp:315:2
    #4 0x672ef4 in main /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/sdl/sdlmain.cpp:215:7
    #5 0x7f711a0f32b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

Direct leak of 34 byte(s) in 1 object(s) allocated from:
    #0 0x531da8 in __interceptor_malloc (/mame/mame0193-321-gf4f8d79998-dirty-tiny+0x531da8)
    #1 0x1d2bc21 in core_strdup(char const*) /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/lib/util/corestr.cpp:130:17
    #2 0x69d9c1 in osd_common_t::update_option(char const*, std::vector<char const*, std::allocator<char const*> >&) const /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/modules/lib/osdobj_common.cpp:374:33
    #3 0x69b738 in osd_common_t::register_options() /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/modules/lib/osdobj_common.cpp:297:2
    #4 0x672ef4 in main /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/sdl/sdlmain.cpp:215:7
    #5 0x7f711a0f32b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

Direct leak of 33 byte(s) in 1 object(s) allocated from:
    #0 0x531da8 in __interceptor_malloc (/mame/mame0193-321-gf4f8d79998-dirty-tiny+0x531da8)
    #1 0x1d2bc21 in core_strdup(char const*) /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/lib/util/corestr.cpp:130:17
    #2 0x69d9c1 in osd_common_t::update_option(char const*, std::vector<char const*, std::allocator<char const*> >&) const /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/modules/lib/osdobj_common.cpp:374:33
    #3 0x69c7b0 in osd_common_t::register_options() /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/modules/lib/osdobj_common.cpp:343:2
    #4 0x672ef4 in main /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/sdl/sdlmain.cpp:215:7
    #5 0x7f711a0f32b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

Direct leak of 28 byte(s) in 1 object(s) allocated from:
    #0 0x531da8 in __interceptor_malloc (/mame/mame0193-321-gf4f8d79998-dirty-tiny+0x531da8)
    #1 0x1d2bc21 in core_strdup(char const*) /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/lib/util/corestr.cpp:130:17
    #2 0x69d9c1 in osd_common_t::update_option(char const*, std::vector<char const*, std::allocator<char const*> >&) const /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/modules/lib/osdobj_common.cpp:374:33
    #3 0x69b45f in osd_common_t::register_options() /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/modules/lib/osdobj_common.cpp:291:2
    #4 0x672ef4 in main /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/sdl/sdlmain.cpp:215:7
    #5 0x7f711a0f32b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

Direct leak of 20 byte(s) in 1 object(s) allocated from:
    #0 0x531da8 in __interceptor_malloc (/mame/mame0193-321-gf4f8d79998-dirty-tiny+0x531da8)
    #1 0x246d588 in pm_alloc /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../3rdparty/portmidi/pm_linux/pmlinux.c:72:35
    #2 0x246f634 in pm_strdup /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../3rdparty/portmidi/pm_linux/pmlinuxalsa.c:715:26
    #3 0x246f634 in pm_linuxalsa_init /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../3rdparty/portmidi/pm_linux/pmlinuxalsa.c:758
    #4 0x246d4b8 in pm_init /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../3rdparty/portmidi/pm_linux/pmlinux.c:39:2
    #5 0x2469468 in Pm_Initialize /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../3rdparty/portmidi/pm_common/portmidi.c:330:9
    #6 0x6a3868 in pm_module::init(osd_options const&) /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/modules/midi/portmidi.cpp:71:2
    #7 0x26fdaeb in osd_module_manager::init(osd_options const&) /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/modules/osdmodule.cpp:77:18
    #8 0x6a0037 in osd_common_t::init_subsystems() /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/modules/lib/osdobj_common.cpp:679:12
    #9 0x673fd1 in sdl_osd_interface::init(running_machine&) /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/sdl/sdlmain.cpp:500:16
    #10 0x18d5f98 in running_machine::start() /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/emu/machine.cpp:207:18
    #11 0x18d9924 in running_machine::run(bool) /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/emu/machine.cpp:303:3
    #12 0x867a94 in mame_machine_manager::execute() /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/frontend/mame/mame.cpp:236:19
    #13 0x9a9afb in cli_frontend::start_execution(mame_machine_manager*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/frontend/mame/clifront.cpp:257:22
    #14 0x9ac2a0 in cli_frontend::execute(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/frontend/mame/clifront.cpp:273:3
    #15 0x869e66 in emulator_info::start_frontend(emu_options&, osd_interface&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/frontend/mame/mame.cpp:336:18
    #16 0x672f02 in main /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/sdl/sdlmain.cpp:216:9
    #17 0x7f711a0f32b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

Direct leak of 20 byte(s) in 1 object(s) allocated from:
    #0 0x531da8 in __interceptor_malloc (/mame/mame0193-321-gf4f8d79998-dirty-tiny+0x531da8)
    #1 0x246d588 in pm_alloc /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../3rdparty/portmidi/pm_linux/pmlinux.c:72:35
    #2 0x246f531 in pm_strdup /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../3rdparty/portmidi/pm_linux/pmlinuxalsa.c:715:26
    #3 0x246f531 in pm_linuxalsa_init /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../3rdparty/portmidi/pm_linux/pmlinuxalsa.c:769
    #4 0x246d4b8 in pm_init /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../3rdparty/portmidi/pm_linux/pmlinux.c:39:2
    #5 0x2469468 in Pm_Initialize /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../3rdparty/portmidi/pm_common/portmidi.c:330:9
    #6 0x6a3868 in pm_module::init(osd_options const&) /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/modules/midi/portmidi.cpp:71:2
    #7 0x26fdaeb in osd_module_manager::init(osd_options const&) /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/modules/osdmodule.cpp:77:18
    #8 0x6a0037 in osd_common_t::init_subsystems() /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/modules/lib/osdobj_common.cpp:679:12
    #9 0x673fd1 in sdl_osd_interface::init(running_machine&) /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/sdl/sdlmain.cpp:500:16
    #10 0x18d5f98 in running_machine::start() /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/emu/machine.cpp:207:18
    #11 0x18d9924 in running_machine::run(bool) /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/emu/machine.cpp:303:3
    #12 0x867a94 in mame_machine_manager::execute() /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/frontend/mame/mame.cpp:236:19
    #13 0x9a9afb in cli_frontend::start_execution(mame_machine_manager*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/frontend/mame/clifront.cpp:257:22
    #14 0x9ac2a0 in cli_frontend::execute(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/frontend/mame/clifront.cpp:273:3
    #15 0x869e66 in emulator_info::start_frontend(emu_options&, osd_interface&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/frontend/mame/mame.cpp:336:18
    #16 0x672f02 in main /mame/build/projects/sdl/mametiny/gmake-linux-clang/../../../../../src/osd/sdl/sdlmain.cpp:216:9
    #17 0x7f711a0f32b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

Direct leak of 10 byte(s) in 1 object(s) allocated from:
    #0 0x531da8 in __interceptor_malloc (/mame/mame0193-321-gf4f8d79998-dirty-tiny+0x531da8)
    #1 0x7f711d3d864b  (/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0+0x5564b)

Indirect leak of 1760 byte(s) in 55 object(s) allocated from:
    #0 0x531fa0 in calloc (/mame/mame0193-321-gf4f8d79998-dirty-tiny+0x531fa0)
    #1 0x7f710bd77899  (/usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so+0x6fc899)

Indirect leak of 64 byte(s) in 2 object(s) allocated from:
    #0 0x531fa0 in calloc (/mame/mame0193-321-gf4f8d79998-dirty-tiny+0x531fa0)
    #1 0x7f710bd76c63  (/usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so+0x6fbc63)

SUMMARY: AddressSanitizer: 10708 byte(s) leaked in 83 allocation(s).
```

**Comment by firewave** [comment]
All of these are leaks are already logged in other reports, are intentional or are not caused by MAME itself.

**Comment by katananja** [comment]
Thank you.
