### ISSUE TITLE
hp_ipc - assertion failure in hp1ll3_device::write

### ISSUE THREAD

**Issue by cuavas** [mamedev/mame#3523]
In a debug build (as at 1f0046d2d0b3dc35bd185886b41a4d48bd7c80f9), the `hp_ipc` `hp9808a` driver will crash immediately on start with an assertion failure:

```
hp ipc os 82991a.bin ROM NEEDS REDUMP
WARNING: the machine might not run correctly.
Assertion failed: ((m_conf_ptr >> 1) < ARRAY_LENGTH(m_conf)), function write, file ../../../../../src/devices/video/hp1ll3.cpp, line 572.

Thread 1 received signal SIGABRT, Aborted.
0x00007fff88a530b6 in __kill () from /usr/lib/libSystem.B.dylib
(gdb) where
#0  0x00007fff88a530b6 in __kill () from /usr/lib/libSystem.B.dylib
#1  0x00007fff88af39f6 in abort () from /usr/lib/libSystem.B.dylib
#2  0x00007fff88ae09bc in __assert_rtn () from /usr/lib/libSystem.B.dylib
#3  0x0000000105ea7c81 in hp1ll3_device::write(address_space&, unsigned int, unsigned char, unsigned char) ()
#4  0x000000010612c823 in handler_entry_write::write_stub_16(address_space&, unsigned int, unsigned short, unsigned short) ()
#5  0x0000000106140f4d in address_space_specific<unsigned short, (endianness_t)1, 0, true>::write_native(unsigned int, unsigned short, unsigned short) ()
#6  0x0000000106140f4d in address_space_specific<unsigned short, (endianness_t)1, 0, true>::write_native(unsigned int, unsigned short, unsigned short) ()
#7  0x0000000105391d28 in m68000_base_device::m68k_op_move_8_ai_d() ()
#8  0x000000010533327c in m68000_base_device::execute_run() ()
#9  0x0000000106276a78 in device_scheduler::timeslice() ()
#10 0x00000001062241b8 in running_machine::run(bool) ()
#11 0x000000010444b0ac in mame_machine_manager::execute() ()
#12 0x00000001042f7af1 in cli_frontend::start_execution(mame_machine_manager*, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) ()
#13 0x00000001042f927d in cli_frontend::execute(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&) ()
#14 0x000000010444bb5c in emulator_info::start_frontend(emu_options&, osd_interface&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&) ()
#15 0x00000001042e3228 in main ()
```

This will be causing data corruption in release builds as it will be writing past the end of the `m_conf` array.

**Comment by cuavas** [comment]
Addressed in #3547
