### ISSUE TITLE
segfault right-clicking in debugger memory view

### ISSUE THREAD

**Issue by fenugrec** [mamedev/mame#4276]
Just hit a segfault (repeatable) while developping a new driver (hp3478a branch on my github fork). 
Very simple at the moment, it's just an MCS48 core with banked ROM.

I'm running my driver like this
"./hp3478a64 -debug", and working with a few debugger windows. In a Memory View window, I selected one of the CPU's registers (:maincpu/0/m_p2), and accidentally right-clicked in the hex view. Instant segfaut, here's the bt : (sorry, my build doesn't have much debugging information)

```
gdb) i s
#0  0x000055555583413a in DebuggerMemView::mousePressEvent(QMouseEvent*) ()
#1  0x00007ffff73d113f in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#2  0x00007ffff7476cef in QFrame::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#3  0x00007ffff69b390b in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*)
    () from /usr/lib/libQt5Core.so.5
#4  0x00007ffff7390e04 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#5  0x00007ffff739892a in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#6  0x00007ffff69b3bf9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /usr/lib/libQt5Core.so.5
#7  0x00007ffff7397c11 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib/libQt5Widgets.so.5
#8  0x00007ffff73eb98c in ?? () from /usr/lib/libQt5Widgets.so.5
#9  0x00007ffff73ee5d5 in ?? () from /usr/lib/libQt5Widgets.so.5
#10 0x00007ffff7390e14 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#11 0x00007ffff73986e1 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/libQt5Widgets.so.5
#12 0x00007ffff69b3bf9 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /usr/lib/libQt5Core.so.5
#13 0x00007ffff6dc10dc in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
#14 0x00007ffff6dc3066 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/libQt5Gui.so.5
#15 0x00007ffff6d9ca3c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#16 0x00007fffba304e1d in ?? () from /usr/lib/libQt5XcbQpa.so.5
#17 0x00007ffff69b3d32 in QCoreApplication::processEvents(QFlags<QEventLoop::ProcessEventsFlag>, int) () from /usr/lib/libQt5Core.so.5
#18 0x0000555555824ced in debug_qt::wait_for_debugger(device_t&, bool) ()
#19 0x0000555555a776e1 in device_debug::instruction_hook(unsigned int) ()
#20 0x0000555555a2d804 in mcs48_cpu_device::execute_run() ()
#21 0x00005555566db251 in device_scheduler::timeslice() ()
#22 0x0000555556685c88 in running_machine::run(bool) ()
#23 0x000055555583d12d in mame_machine_manager::execute() ()
#24 0x00005555558cec74 in cli_frontend::start_execution(mame_machine_manager*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) ()
#25 0x00005555558ceeee in cli_frontend::execute(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) ()
#26 0x000055555583b1e5 in emulator_info::start_frontend(emu_options&, osd_interface&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) ()
#27 0x0000555555754b44 in main ()
```

If needed I can run different tests, but it's very complicated for me to recompile the whole thing due to luaengine.cpp, so I'd like to keep full recompiles to a minimum !

**Comment by cuavas** [comment]
This was fixed by 83c9637635c575972c039d7d63a48d788e41ba34.
