### ISSUE TITLE
[neogeo] Changing machines display crosshatch screen and further segmentation fault

### ISSUE THREAD

**Issue by katananja** [mamedev/mame#4520]
``mame0205-471-g94c640c0eb-dirty``
Debian 9.6 x64
Compile options:
``make clean && make SYMBOLS=1 SYMLEVEL=1 OPTIMIZE=0``

- ``./mame64 -verbose kof99``
- TAB > Select New Machine > The King Of Fighters 2000 (kof2000)
- It display the self-test crosshatch screen.
- If you try to go any further to select another machine, you receive a segmentation fault.
- TAB > Select New Machine > The King Of Fighters 2001 (kof2001)

```
Thread 1 "mame64" received signal SIGSEGV, Segmentation fault.
─── Assembly 
───────────────────────────────────────────────────────────────────
0x00007ffff44ac380 _int_malloc+1760 mov    0x28(%rax),%r14
0x00007ffff44ac384 _int_malloc+1764 jmp    0x7ffff44ac38a <_int_malloc+1770>
0x00007ffff44ac386 _int_malloc+1766 mov    0x28(%r14),%r14
0x00007ffff44ac38a _int_malloc+1770 mov    0x8(%r14),%rax
0x00007ffff44ac38e _int_malloc+1774 mov    %rax,%rbp
0x00007ffff44ac391 _int_malloc+1777 and    $0xfffffffffffffff8,%rbp
0x00007ffff44ac395 _int_malloc+1781 cmp    %rbp,%r12
─── Expressions ────────────────────────────────────────────────────────────────
─── History ────────────────────────────────────────────────────────────────────
─── Memory ─────────────────────────────────────────────────────────────────────
─── Registers ──────────────────────────────────────────────────────────────────
   rax 0x000055556d1326c0     rbx 0x00007ffff47ccb58     rcx 0x00007ffff47cd328 
   rdx 0x00007ffff47cd338     rsi 0x0000000000000050     rdi 0x00007ffff47ccb98 
   rbp 0x000000000000270e     rsp 0x00007fffffff5790      r8 0x00007ffff47ccb98 
    r9 0x0000000004000010     r10 0x0000000000000090     r11 0xdb6e0f70ddbfd78c 
   r12 0x0000000004000010     r13 0x00007ffff47ccb58     r14 0xec0ade9400000000 
   r15 0x00007ffff47ccb00     rip 0x00007ffff44ac38a  eflags [ CF IF RF ]       
    cs 0x00000033              ss 0x0000002b              ds 0x00000000         
    es 0x00000000              fs 0x00000000              gs 0x00000000         
─── Source ─────────────────────────────────────────────────────────────────────
Cannot display "/build/glibc-yWQXbR/glibc-2.24/malloc/malloc.c" ([Errno 2] File or directory not found : '/build/glibc-yWQXbR/glibc-2.24/malloc/malloc.c')
─── Stack ──────────────────────────────────────────────────────────────────────
[0] from 0x00007ffff44ac38a in _int_malloc+1770 at malloc.c:3650
arg av = 0x7ffff47ccb00 <main_arena>
arg bytes = 67108864
[1] from 0x00007ffff44adf64 in __GI___libc_malloc+84 at malloc.c:2928
arg bytes = 67108864
[+]
─── Threads ────────────────────────────────────────────────────────────────────
[23] id 30512 name SDLAudioDev1 from 0x00007ffff4512741 in __GI_ppoll+145 at ../sysdeps/unix/sysv/linux/ppoll.c:39
[22] id 30511 name PulseHotplug from 0x00007ffff4512741 in __GI_ppoll+145 at ../sysdeps/unix/sysv/linux/ppoll.c:39
[21] id 30510 name si_shader:3 from 0x00007ffff74a115f in pthread_cond_wait@@GLIBC_2.3.2 at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
[20] id 30509 name si_shader:2 from 0x00007ffff74a115f in pthread_cond_wait@@GLIBC_2.3.2 at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
[19] id 30508 name si_shader:1 from 0x00007ffff74a115f in pthread_cond_wait@@GLIBC_2.3.2 at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
[18] id 30507 name si_shader:0 from 0x00007ffff74a115f in pthread_cond_wait@@GLIBC_2.3.2 at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
[17] id 30506 name radeon_cs:0 from 0x00007ffff74a115f in pthread_cond_wait@@GLIBC_2.3.2 at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
[1] id 29907 name mame64 from 0x00007ffff44ac38a in _int_malloc+1770 at malloc.c:3650
```

This also happens on Windows but it only display a "segmentation fault" message.

**Comment by cuavas** [comment]
Please run the test case under a debugger and provide a stack trace for the crashed thread.  All builds contain function name symbols at a minimum.

**Comment by katananja** [comment]
```
==2227==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7f6b8d4a6800 at pc 0x0000019a963e bp 0x7ffd4dd2d450 sp 0x7ffd4dd2d448
READ of size 2 at 0x7f6b8d4a6800 thread T0
    #0 0x19a963d in sma_prot_device::kof99_decrypt_68k(unsigned char*) /home/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/devices/bus/neogeo/prot_sma.cpp:426:24
    #1 0x15e7b10 in neogeo_sma_kof99_cart_device::decrypt_all(unsigned char*, unsigned int, unsigned char*, unsigned int, unsigned char*, unsigned int, unsigned char*, unsigned int, unsigned char*, unsigned int, unsigned char*, unsigned int, unsigned char*, unsigned int) /home/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/devices/bus/neogeo/sma.cpp:75:14
    #2 0x15e7cd5 in non-virtual thunk to neogeo_sma_kof99_cart_device::decrypt_all(unsigned char*, unsigned int, unsigned char*, unsigned int, unsigned char*, unsigned int, unsigned char*, unsigned int, unsigned char*, unsigned int, unsigned char*, unsigned int, unsigned char*, unsigned int) /home/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/devices/bus/neogeo/sma.cpp
    #3 0x6232c5 in neogeo_cart_slot_device::late_decrypt_all() /home/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/devices/bus/neogeo/slot.h:327:48
    #4 0x5caeb6 in neogeo_base_state::set_slot_idx(int) /home/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/mame/drivers/neogeo.cpp:1396:26
    #5 0x5d7f7d in mvs_state::machine_start() /home/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/mame/drivers/neogeo.cpp:1598:2
    #6 0x5d7ffe in mvs_led_state::machine_start() /home/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/mame/drivers/neogeo.cpp:1606:13
    #7 0x1f93071 in driver_device::device_start() /home/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/emu/driver.cpp:236:3
    #8 0x1de8069 in device_t::start() /home/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/emu/device.cpp:551:2
    #9 0x45ef6c2 in running_machine::start_all_devices() /home/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/emu/machine.cpp:1035:13
    #10 0x45edef8 in running_machine::start() /home/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/emu/machine.cpp:263:2
    #11 0x45f04d0 in running_machine::run(bool) /home/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/emu/machine.cpp:308:3
    #12 0x9e9522 in mame_machine_manager::execute() /home/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/frontend/mame/mame.cpp:239:19
    #13 0xca1383 in cli_frontend::start_execution(mame_machine_manager*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) /home/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/frontend/mame/clifront.cpp:262:22
    #14 0xca40ea in cli_frontend::execute(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) /home/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/frontend/mame/clifront.cpp:278:3
    #15 0x9eafba in emulator_info::start_frontend(emu_options&, osd_interface&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) /home/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/frontend/mame/mame.cpp:339:18
    #16 0x6a2b06 in main /home/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/osd/sdl/sdlmain.cpp:217:9
    #17 0x7f6bc060b2e0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202e0)
    #18 0x4cee09 in _start (/home/mame/mame64+0x4cee09)

0x7f6b8d4a6800 is located 0 bytes to the right of 5242880-byte region [0x7f6b8cfa6800,0x7f6b8d4a6800)
allocated by thread T0 here:
    #0 0x5c3038 in operator new(unsigned long) (/home/mame/mame64+0x5c3038)
    #1 0x6a127b in __gnu_cxx::new_allocator<unsigned char>::allocate(unsigned long, void const*) /usr/bin/../lib64/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/ext/new_allocator.h:104:27
    #2 0x6a121b in std::allocator_traits<std::allocator<unsigned char> >::allocate(std::allocator<unsigned char>&, unsigned long) /usr/bin/../lib64/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/alloc_traits.h:436:20
    #3 0x6a0ba2 in std::_Vector_base<unsigned char, std::allocator<unsigned char> >::_M_allocate(unsigned long) /usr/bin/../lib64/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/stl_vector.h:170:20
    #4 0x14317fe in std::_Vector_base<unsigned char, std::allocator<unsigned char> >::_M_create_storage(unsigned long) /usr/bin/../lib64/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/stl_vector.h:185:33
    #5 0x1431634 in std::_Vector_base<unsigned char, std::allocator<unsigned char> >::_Vector_base(unsigned long, std::allocator<unsigned char> const&) /usr/bin/../lib64/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/stl_vector.h:136:9
    #6 0x142a216 in std::vector<unsigned char, std::allocator<unsigned char> >::vector(unsigned long, std::allocator<unsigned char> const&) /usr/bin/../lib64/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/stl_vector.h:280:9
    #7 0x1fbfbf9 in memory_region::memory_region(running_machine&, char const*, unsigned int, unsigned char, endianness_t) /home/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/emu/emumem.cpp:2896:3
    #8 0x1fcb549 in std::_MakeUniq<memory_region>::__single_object std::make_unique<memory_region, running_machine&, char const*&, unsigned int&, unsigned char&, endianness_t&>(running_machine&, char const*&, unsigned int&, unsigned char&, endianness_t&) /usr/bin/../lib64/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/unique_ptr.h:791:34
    #9 0x1fa024d in memory_manager::region_alloc(char const*, unsigned int, unsigned char, endianness_t) /home/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/emu/emumem.cpp:884:29
    #10 0x475f705 in rom_load_manager::process_region_list() /home/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/emu/romload.cpp:1429:35
    #11 0x4761592 in rom_load_manager::rom_load_manager(running_machine&) /home/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/emu/romload.cpp:1519:2
    #12 0x45fccdc in MakeUniqClearT<rom_load_manager>::single_object make_unique_clear<rom_load_manager, running_machine&>(running_machine&) /home/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/lib/util/corealloc.h:74:38
    #13 0x45ed6ba in running_machine::start() /home/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/emu/machine.cpp:232:15
    #14 0x45f04d0 in running_machine::run(bool) /home/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/emu/machine.cpp:308:3
    #15 0x9e9522 in mame_machine_manager::execute() /home/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/frontend/mame/mame.cpp:239:19
    #16 0xca1383 in cli_frontend::start_execution(mame_machine_manager*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) /home/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/frontend/mame/clifront.cpp:262:22
    #17 0xca40ea in cli_frontend::execute(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) /home/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/frontend/mame/clifront.cpp:278:3
    #18 0x9eafba in emulator_info::start_frontend(emu_options&, osd_interface&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) /home/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/frontend/mame/mame.cpp:339:18
    #19 0x6a2b06 in main /home/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/osd/sdl/sdlmain.cpp:217:9
    #20 0x7f6bc060b2e0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202e0)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/mame/build/projects/sdl/mame/gmake-linux-clang/../../../../../src/devices/bus/neogeo/prot_sma.cpp:426:24 in sma_prot_device::kof99_decrypt_68k(unsigned char*)
Shadow bytes around the buggy address:
  0x0fedf1a8ccb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fedf1a8ccc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fedf1a8ccd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fedf1a8cce0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fedf1a8ccf0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0fedf1a8cd00:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fedf1a8cd10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fedf1a8cd20: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fedf1a8cd30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fedf1a8cd40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0fedf1a8cd50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==2227==ABORTING
```

**Comment by Robbbert** [comment]
This issue logged as https://mametesters.org/view.php?id=7208

Further correspondence can be done there.
