### ISSUE TITLE
MAME quits when minimized

### ISSUE THREAD

**Issue by katananja** [mamedev/mame#4763]
`MAME v0.207 (mame0207-327-gfae6abca59)`
Windows 10 x64 1803 (17134.590)
GCC 8.3.0
Build options: `rm -rf build && make -j5`
Run command: `mame64.exe -w -maximize`

Run MAME then minimize the window.
`Fatal error: Too many live texture instances! (../../../../../src/emu/render.cpp:498)`

No gdb info available:

```
gdb mame64.exe
GNU gdb (GDB) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from mame64.exe...(no debugging symbols found)...done.
(gdb) run
Starting program: D:\Mame\mame64.exe
[New Thread 6080.0x704]
...
[Thread 6080.0x11a8 exited with code 0]
warning: Too many live texture instances! (../../../../../src/emu/render.cpp:498)

Thread 1 received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffabbccc643 in KERNELBASE!DebugBreak () from C:\Windows\System32\KernelBase.dll
(gdb) where
#0  0x00007ffabbccc643 in KERNELBASE!DebugBreak () from C:\Windows\System32\KernelBase.dll
#1  0x000000000552b2cf in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```
Some extra:
```
(gdb) add-symbol-file mame64.sym
add symbol table from file "mame64.sym"
(y or n) y
`D:\Mame\mame64.sym': can't read symbols: file format not recognized.

objdump -D mame64.exe | grep .text
Disassembly of section .text:
0000000000401000 <.text>:

gdb mame64.exe
...
add-symbol-file mame64.sym 0x401000
(gdb) add-symbol-file mame64.sym 0x401000
add symbol table from file "mame64.sym" at
        .text_addr = 0x401000
(y or n) y
`D:\Mame\mame64.sym': can't read symbols: file format not recognized.
```
This is Microsoft Windows specific.

**Comment by Tafoid** [comment]
D3D specific issue.
https://mametesters.org/view.php?id=6264 and others
https://github.com/mamedev/mame/issues/2421

Already logged.
Closing

**Comment by katananja** [comment]
This is happening also with other video modes.

```
mame64 -video bgfx
Fatal error: Too many live texture instances! (../../../../../src/emu/render.cpp:498)
mame64 -video opengl
Fatal error: Too many live texture instances! (../../../../../src/emu/render.cpp:498)
mame64 -video gdi
Fatal error: Too many live texture instances! (../../../../../src/emu/render.cpp:498)
```

**Comment by Robbbert** [comment]
MT 06264 has been updated with the new info.

**Comment by katananja** [comment]
Thank you @Robbbert

**Comment by Pauweltje** [comment]
So many people having this problem..so less solutions!

**Comment by Robbbert** [comment]
Problem has been resolved. If you are still having problems, verify it against 0.211 (when released) and log a report at Mametesters.
