### ISSUE TITLE
[BGFX] Segmentation fault

### ISSUE THREAD

**Issue by katananja** [mamedev/mame#4789]
Windows 10 x64 1803 (17134.590)
Clang 7.0.1
Python 2.7.16
Build options: `make clean && make OVERRIDE_CC=/mingw64/bin/clang OVERRIDE_CXX=/mingw64/bin/clang++ SUBTARGET=tiny SYMBOLS=1 SYMLEVEL=1 OPTIMIZE=0 -j5`

MAME crash with `-video bgfx`
The folder `bgfx` it's up to date.

`mametiny64 -video bgfx`
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x0000000000bd9153 in submit () at ../../../../../3rdparty/bgfx/src\bgfx.cpp:1216
1216                    m_frame->m_renderItem[renderItemIdx].draw = m_draw;
(gdb) where
#0  0x0000000000bd9153 in submit () at ../../../../../3rdparty/bgfx/src\bgfx.cpp:1216
#1  0x0000000000be28b3 in submit () at ../../../../../3rdparty/bgfx/src\bgfx.cpp:3530
#2  submit () at ../../../../../3rdparty/bgfx/src\bgfx.cpp:4708
#3  submit () at ../../../../../3rdparty/bgfx/src\bgfx.cpp:4702
#4  0x00000000004a3ab2 in submit () at ../../../../../src/osd/modules/render/bgfx\effect.cpp:49
#5  0x0000000000488fa9 in draw () at ../../../../../src/osd/modules/render\drawbgfx.cpp:863
#6  0x000000000046d495 in draw_video_contents () at ../../../../../src/osd/windows\window.cpp:1395
#7  0x000000000046cb8d in video_window_proc () at ../../../../../src/osd/windows\window.cpp:1318
#8  0x000000000046e07f in winwindow_video_window_proc_ui(HWND__*, unsigned int, unsigned long long, long long) ()
    at ../../../../../src/osd/windows\winmenu.cpp:23
#9  0x00007ffd65886d41 in USER32!CallWindowProcW () from C:\Windows\System32\user32.dll
#10 0x00007ffd6588690b in USER32!CallWindowProcW () from C:\Windows\System32\user32.dll
#11 0x00007ffd3d37478f in DllUnregisterServer () from C:\Windows\SYSTEM32\dinput8.dll
#12 0x00007ffd3d3748d4 in DllUnregisterServer () from C:\Windows\SYSTEM32\dinput8.dll
#13 0x00007ffd3d37478f in DllUnregisterServer () from C:\Windows\SYSTEM32\dinput8.dll
#14 0x00007ffd3d374b4a in DllUnregisterServer () from C:\Windows\SYSTEM32\dinput8.dll
#15 0x00007ffd65886d41 in USER32!CallWindowProcW () from C:\Windows\System32\user32.dll
#16 0x00007ffd6588634e in USER32!SendMessageW () from C:\Windows\System32\user32.dll
#17 0x00007ffd658860d8 in USER32!SendMessageW () from C:\Windows\System32\user32.dll
#18 0x00007e1100025ae7 in SetLoadLibraryCallback () from D:\cmder_mini\vendor\conemu-maximus5\ConEmu\ConEmuHk64.dll
#19 0x000000000046c473 in update () at ../../../../../src/osd/windows\window.cpp:891
#20 0x0000000000469e2f in update () at ../../../../../src/osd/windows\video.cpp:94
#21 0x00000000008b87a5 in frame_update () at ../../../../../src/emu\video.cpp:251
#22 0x00000000005106ad in set_startup_text () at ../../../../../src/frontend/mame/ui\ui.cpp:382
#23 0x00000000004de6d3 in create_ui () at ../../../../../src/frontend/mame\mame.cpp:291
#24 0x00000000008609e3 in start () at ../../../../../src/emu\machine.cpp:208
#25 0x0000000000861d4f in run () at ../../../../../src/emu\machine.cpp:308
#26 0x00000000004ddf9a in execute () at ../../../../../src/frontend/mame\mame.cpp:239
#27 0x000000000053999f in start_execution () at ../../../../../src/frontend/mame\clifront.cpp:262
#28 0x000000000053aae5 in execute () at ../../../../../src/frontend/mame\clifront.cpp:278
#29 0x00000000004deadf in emulator_info::start_frontend(emu_options&, osd_interface&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) () at ../../../../../src/frontend/mame\mame.cpp:339
#30 0x000000000045bd93 in main () at ../../../../../src/osd/windows\winmain.cpp:323
```

**Comment by katananja** [comment]
Looks like this is also happening with Linux, one other thing that I've noticed, it only happens if MAME it's compiled with Clang, with GCC there's no segmentation fault.
```
Thread 1 "mame64" received signal SIGSEGV, Segmentation fault.
─── Assembly ───────────────────────────────────────────────────────────────────
0x00000000073fbb7f submit+687 mov    (%r15),%rax
0x00000000073fbb82 submit+690 mov    %r8,%rcx
0x00000000073fbb85 submit+693 shl    $0x7,%rcx
0x00000000073fbb89 submit+697 vmovaps (%r11),%ymm0
0x00000000073fbb8e submit+702 vmovaps 0x20(%r11),%ymm1
0x00000000073fbb94 submit+708 vmovaps 0x40(%r11),%ymm2
0x00000000073fbb9a submit+714 vmovaps 0x60(%r11),%ymm3
─── Expressions ────────────────────────────────────────────────────────────────
─── History ────────────────────────────────────────────────────────────────────
─── Memory ─────────────────────────────────────────────────────────────────────
─── Registers ──────────────────────────────────────────────────────────────────
   rax 0x00007fffe81792c0     rbx 0x0000000000000000     rcx 0x0000000000000000 
   rdx 0x0000000000000006     rsi 0x0000000000000000     rdi 0x0000000000000001 
   rbp 0x00007fffffff71f0     rsp 0x00007fffffff71d0      r8 0x0000000000000000 
    r9 0x0000000000000000     r10 0x000000000000ffff     r11 0x000000000d9863d0 
   r12 0x00007fffffff7220     r13 0x0000000000000005     r14 0x00007fffe81792c0 
   r15 0x000000000d986390     rip 0x00000000073fbb89  eflags [ PF AF ZF IF RF ] 
    cs 0x00000033              ss 0x0000002b              ds 0x00000000         
    es 0x00000000              fs 0x00000000              gs 0x00000000         
─── Source ─────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "<string>", line 388, in render
  File "<string>", line 897, in lines
TypeError: unorderable types: float() > NoneType()
─── Stack ──────────────────────────────────────────────────────────────────────
[0] from 0x00000000073fbb89 in submit+697 at ../../../../../3rdparty/bgfx/src/bgfx.cpp:1216
(no arguments)
[1] from 0x00000000074048f9 in submit+36905 at ../../../../../3rdparty/bgfx/src/bgfx.cpp:3530
(no arguments)
[+]
─── Threads ────────────────────────────────────────────────────────────────────
[9] id 16937 name SDLAudioDev1 from 0x00007ffff4511981 in __GI_ppoll+145 at ../sysdeps/unix/sysv/linux/ppoll.c:39
[8] id 16936 name PulseHotplug from 0x00007ffff4511981 in __GI_ppoll+145 at ../sysdeps/unix/sysv/linux/ppoll.c:39
[7] id 16935 name si_shader:3 from 0x00007ffff719d17f in pthread_cond_wait@@GLIBC_2.3.2 at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
[6] id 16934 name si_shader:2 from 0x00007ffff719d17f in pthread_cond_wait@@GLIBC_2.3.2 at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
[5] id 16933 name si_shader:1 from 0x00007ffff719d17f in pthread_cond_wait@@GLIBC_2.3.2 at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
[4] id 16932 name si_shader:0 from 0x00007ffff719d17f in pthread_cond_wait@@GLIBC_2.3.2 at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
[3] id 16931 name radeon_cs:0 from 0x00007ffff719d17f in pthread_cond_wait@@GLIBC_2.3.2 at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
[2] id 16930 name mame64 from 0x00007ffff719d528 in pthread_cond_timedwait@@GLIBC_2.3.2 at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
[1] id 16929 name mame64 from 0x00000000073fbb89 in submit+697 at ../../../../../3rdparty/bgfx/src/bgfx.cpp:1216
────────────────────────────────────────────────────────────────────────────────
>>> where
#0  0x00000000073fbb89 in submit () at ../../../../../3rdparty/bgfx/src/bgfx.cpp:1216
#1  0x00000000074048f9 in submit () at ../../../../../3rdparty/bgfx/src/bgfx.cpp:3530
#2  submit () at ../../../../../3rdparty/bgfx/src/bgfx.cpp:4708
#3  submit () at ../../../../../3rdparty/bgfx/src/bgfx.cpp:4702
#4  0x0000000004141bf1 in submit () at ../../../../../src/osd/modules/render/bgfx/effect.cpp:49
#5  0x00000000040fc72c in draw () at ../../../../../src/osd/modules/render/drawbgfx.cpp:863
#6  0x00000000040e1ba3 in update () at ../../../../../src/osd/sdl/window.cpp:629
#7  0x00000000040de3ba in update () at ../../../../../src/osd/sdl/video.cpp:108
#8  0x0000000006f20f45 in frame_update () at ../../../../../src/emu/video.cpp:251
#9  0x00000000041ca315 in set_startup_text () at ../../../../../src/frontend/mame/ui/ui.cpp:382
#10 0x000000000418529c in create_ui () at ../../../../../src/frontend/mame/mame.cpp:291
#11 0x0000000006e9efe4 in start () at ../../../../../src/emu/machine.cpp:208
#12 0x0000000006ea0528 in run () at ../../../../../src/emu/machine.cpp:308
#13 0x0000000004184ba8 in execute () at ../../../../../src/frontend/mame/mame.cpp:239
#14 0x00000000041f79a9 in start_execution () at ../../../../../src/frontend/mame/clifront.cpp:262
#15 0x00000000041f89a2 in execute () at ../../../../../src/frontend/mame/clifront.cpp:278
#16 0x00000000041856c1 in emulator_info::start_frontend(emu_options&, osd_interface&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&) () at ../../../../../src/frontend/mame/mame.cpp:339
#17 0x00000000040dca76 in main () at ../../../../../src/osd/sdl/sdlmain.cpp:217
```

**Comment by MooglyGuy** [comment]
The callstack indicates that the crash is occurring inside the 3rd-party BGFX code, not inside MAME itself. File an issue with the BGFX project.

**Comment by katananja** [comment]
That is a superficial analysis because the stack it is also pointing out to 14 stacks inside MAME code.

Since it's a segmentation fault and **MAME it's crashing**, we all know that 'something' it's trying to do an illegal read or write inside MAME memory space, otherwise it would be just bgfx's that isn't the case here, so it doesn't justify closing a legit bug report, just because.

The regression comes from your commit 0bd02131b644b61088789f52f31b750c9aecaa6d before that MAME don't crash, I've just tested out.

It's your commit, you implemented, so you go and you file an issue with the BGFX project.

**Comment by MooglyGuy** [comment]
I do not use Linux and am not inclined to fix this, particularly with your ever-abusive attitude towards people who actually contribute to this project.

**Comment by cuavas** [comment]
0bd02131b644b61088789f52f31b750c9aecaa6d is an update to bgfx from upstream.  If it started happening after that commit, it's a regression in bgfx itself.  MAME isn't doing anything different.  I also can't reproduce this with MAME 0.208 built with clang 6 and libc++ on Fedora 28.  There must be some other contributing factor.

@katananja you really need to work on your attitude.  Your comment is abrasive, and your conclusion doesn't match your findings.
