### ISSUE TITLE
bgfx_backend vulkan: window scaling locks desktop on ubuntu 16.04

### ISSUE THREAD

**Issue by couriersud** [mamedev/mame#5822]
Window scaling doesn't work on ubuntu 16.04 with nvidia-430 when using the bgfx backend vulkan.

Steps to reproduce:
`./mame64  -bgfx_backend vulkan `
After mame started, try to rescale the window using the mouse. 
The desktop will lock up. It remains in this state for approx. 60 seconds. 
Afterwards, no more game/ui display but mame can be closed.

**Comment by belegdol** [comment]
This sounds very similar to how vulkan backend was behaving here without resizing prior to https://github.com/mamedev/mame/commit/ec4bee1371353b2767a1260637ab5317646970ca.

**Comment by belegdol** [comment]
I can confirm this is happening on Fedora 31 and nvidia 435.21 drivers too, and is affecting games outputing palletted video (umk3) as well as ones outputting rgb32 (invqix).

**Comment by belegdol** [comment]
I have managed to obtain a backtrace during the lockup thanks to instructions provided by @cuavas over at bannister.org:

```
#0  0x00007f6034e8ff55 in nanosleep () from /lib64/libpthread.so.0
#1  0x0000000001f9a2b6 in std::this_thread::sleep_for<long, std::ratio<1l, 1000000000l> > (__rtime=...)
    at /usr/include/c++/9/thread:378
#2  osd_sleep (duration=duration@entry=11668463) at ../../../../../src/osd/osdcore.cpp:165
#3  0x0000000001cb8d77 in video_manager::throttle_until_ticks (this=this@entry=0x57b4a40, target_ticks=1572983416621416757)
    at ../../../../../src/emu/video.cpp:1049
#4  0x0000000001cb9120 in video_manager::update_throttle (this=this@entry=0x57b4a40, emutime=...)
    at ../../../../../src/emu/video.cpp:1011
#5  0x0000000001cc101a in video_manager::frame_update (this=0x57b4a40, from_debugger=from_debugger@entry=false)
    at ../../../../../src/emu/attotime.h:99
#6  0x0000000001c821ce in screen_device::vblank_begin (this=0x429e6f0) at /usr/include/c++/9/bits/unique_ptr.h:352
#7  0x0000000001c84b4d in screen_device::device_timer (this=0x429e6f0, timer=..., id=<optimized out>, param=<optimized out>, 
    ptr=<optimized out>) at ../../../../../src/emu/screen.cpp:940
#8  0x0000000001c7c072 in device_t::timer_expired (ptr=<optimized out>, param=<optimized out>, id=<optimized out>, timer=..., 
    this=<optimized out>) at ../../../../../src/emu/device.h:609
#9  device_scheduler::execute_timers (this=<optimized out>) at ../../../../../src/emu/schedule.cpp:894
#10 device_scheduler::timeslice (this=this@entry=0x7fff779391e8) at ../../../../../src/emu/schedule.cpp:534
#11 0x0000000001c25c98 in running_machine::run (this=this@entry=0x7fff77933c70, quiet=quiet@entry=false)
    at ../../../../../src/emu/machine.cpp:367
#12 0x00000000007696d5 in mame_machine_manager::execute (this=this@entry=0x417d460)
    at ../../../../../src/frontend/mame/mame.cpp:261
#13 0x00000000008053ea in cli_frontend::start_execution (this=0x7fff77939ce0, manager=0x417d460, args=...)
    at ../../../../../src/frontend/mame/clifront.cpp:264
#14 0x00000000008055ce in cli_frontend::execute (this=this@entry=0x7fff77939ce0, 
    args=std::vector of length 12, capacity 12 = {...}) at ../../../../../src/frontend/mame/clifront.cpp:280
#15 0x0000000000767988 in emulator_info::start_frontend (options=..., osd=..., args=std::vector of length 12, capacity 12 = {...})
    at ../../../../../src/frontend/mame/mame.cpp:392
#16 0x00000000004f309b in main (argc=<optimized out>, argv=<optimized out>) at ../../../../../src/osd/sdl/sdlmain.cpp:217
```
The full backtrace I am attaching instead of pasting it because it is a lot.
[gdb.txt](https://github.com/mamedev/mame/files/3810959/gdb.txt)

**Comment by couriersud** [comment]
Happens with nvidia 440 driver as well.

**Comment by angelosa** [comment]
Give for granted this has been fixed from a while, reopen if it happens on something that isn't EoL like Ubuntu 16.04.
