### ISSUE TITLE
(Linux, Windows) imgui debugger crashes when trying to mount an image

### ISSUE THREAD

**Issue by belegdol** [mamedev/mame#8350]
I was trying to get the imgui mount window to display in an attempt to finalize https://github.com/mamedev/mame/pull/8035. Unfortunately, mame appears to crash when clicking on Images -> Image -> Mount.... In order to reproduce:
```
$ mame -debug -debugger imgui ikaruga
(debugger) go
click on Images -> Image -> Mount...
```
Here is the backtrace:
```
Thread 1 "mame" received signal SIGSEGV, Segmentation fault.
ImGui::EndGroup () at ../../../../../3rdparty/bgfx/3rdparty/dear-imgui/imgui.cpp:6904
6904	    ImRect group_bb(group_data.BackupCursorPos, ImMax(window->DC.CursorMaxPos, group_data.BackupCursorPos));
(gdb) bt
#0  ImGui::EndGroup () at ../../../../../3rdparty/bgfx/3rdparty/dear-imgui/imgui.cpp:6904
#1  0x0000000001c758d9 in ImGui::ListBoxFooter () at ../../../../../3rdparty/bgfx/3rdparty/dear-imgui/imgui_widgets.cpp:5720
#2  0x000000000058d2ad in debug_imgui::draw_mount_dialog (this=0x2969a90, label=<optimized out>)
    at ../../../../../src/osd/modules/debugger/debugimgui.cpp:1138
#3  0x000000000058d7af in debug_imgui::draw_console (this=0x2969a90) at ../../../../../src/osd/modules/debugger/debugimgui.cpp:1338
#4  0x000000000058deef in debug_imgui::update (this=this@entry=0x2969a90)
    at ../../../../../src/osd/modules/debugger/debugimgui.cpp:1366
#5  0x000000000058e46e in debug_imgui::debugger_update (this=0x2969a90)
    at ../../../../../src/osd/modules/debugger/debugimgui.cpp:1517
#6  0x000000000053a713 in osd_common_t::debugger_update (this=<optimized out>)
    at ../../../../../src/osd/modules/lib/osdobj_common.cpp:527
#7  0x0000000000531e47 in sdl_osd_interface::update (this=0x7fffffffd230, skip_redraw=<optimized out>)
    at ../../../../../src/osd/sdl/video.cpp:114
#8  0x0000000001aa81d3 in video_manager::frame_update (this=0x4a445e0, from_debugger=from_debugger@entry=false)
    at ../../../../../src/emu/video.cpp:239
#9  0x0000000001a6ec9b in screen_device::vblank_begin (this=0x3012290) at ../../../../../src/emu/screen.cpp:1657
#10 0x0000000001a71835 in screen_device::device_timer (this=0x3012290, timer=..., id=<optimized out>, param=<optimized out>, 
    ptr=<optimized out>) at ../../../../../src/emu/screen.cpp:943
#11 0x0000000001a68226 in device_t::timer_expired (ptr=<optimized out>, param=<optimized out>, id=<optimized out>, timer=..., 
    this=<optimized out>) at ../../../../../src/emu/device.h:613
#12 emu_timer::device_timer_expired (timer=..., ptr=<optimized out>, param=<optimized out>)
    at ../../../../../src/emu/schedule.cpp:317
#13 0x0000000001a6c855 in delegate_base<void, void*, int>::operator() (args#1=<optimized out>, args#0=<optimized out>, 
    this=0x8a18f98) at ../../../../../src/lib/util/delegate.h:511
#14 device_scheduler::execute_timers (this=this@entry=0x7fffffffc9b0) at ../../../../../src/emu/schedule.cpp:907
#15 0x0000000001a69229 in device_scheduler::timeslice (this=this@entry=0x7fffffffc9b0) at ../../../../../src/emu/schedule.cpp:544
#16 0x0000000001a115e0 in running_machine::run (this=this@entry=0x7fffffff7560, quiet=quiet@entry=false)
    at ../../../../../src/emu/machine.cpp:381
#17 0x00000000005ea304 in mame_machine_manager::execute (this=this@entry=0x28e98f0)
    at ../../../../../src/frontend/mame/mame.cpp:269
#18 0x000000000067f466 in cli_frontend::start_execution (this=0x7fffffffd1d0, manager=0x28e98f0, args=...)
    at ../../../../../src/frontend/mame/clifront.cpp:271
#19 0x000000000067f61e in cli_frontend::execute (this=this@entry=0x7fffffffd1d0, args=std::vector of length 3, capacity 3 = {...})
    at ../../../../../src/frontend/mame/clifront.cpp:287
#20 0x00000000005e7db8 in emulator_info::start_frontend (options=..., osd=..., args=std::vector of length 3, capacity 3 = {...})
    at ../../../../../src/frontend/mame/mame.cpp:400
#21 0x00000000004b2745 in main (argc=<optimized out>, argv=<optimized out>) at ../../../../../src/osd/sdl/sdlmain.cpp:219
```

**Comment by belegdol** [comment]
The crash happens on Windows too.

**Comment by mahlemiut** [comment]
Pushed a fix for this, mount and create should now work.

**Comment by belegdol** [comment]
Confirmed it works, thanks.
