### ISSUE TITLE
umk3 sound_assert: u32(start) < samples() with DEBUG=1 build

### ISSUE THREAD

**Issue by belegdol** [mamedev/mame#8511]
With `DEBUG=1` build, umk3 hits an assert right after start:
```
$ mame -rompath /mnt/openmediavault/emu/mame/roms/ -window -video bgfx -bgfx_backend opengl -bgfx_path bgfx umk3
...
sound_assert: u32(start) < samples()
MAME exception: sound_assert: u32(start) < samples()

Attempting to fall into debugger

Thread 1 "mamed" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff5e6a59b in kill () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff5e6a59b in kill () from /lib64/libc.so.6
#1  0x0000000001fdd70e in osd_break_into_debugger (message=message@entry=0x2273078 "sound_assert: u32(start) < samples()\n")
    at ../../../../../src/osd/modules/lib/osdlib_unix.cpp:65
#2  0x0000000000dc5f53 in write_stream_view::index_to_buffer_index (start=1, this=0x434c5d0) at ../../../../../src/emu/sound.h:461
#3  write_stream_view::fill (count=0, start=1, value=0, this=0x434c5d0) at ../../../../../src/emu/sound.h:417
#4  write_stream_view::fill (start=1, value=0, this=0x434c5d0) at ../../../../../src/emu/sound.h:424
#5  dmadac_sound_device::sound_stream_update (this=<optimized out>, stream=..., inputs=..., outputs=...)
    at ../../../../../src/devices/sound/dmadac.cpp:196
#6  0x0000000001cbb3bc in delegate_base<void, sound_stream&, std::vector<read_stream_view, std::allocator<read_stream_view> > const&, std::vector<write_stream_view, std::allocator<write_stream_view> >&>::operator() (
    args#2=std::vector of length 1, capacity 1 = {...}, args#1=std::vector of length 0, capacity 0, args#0=..., this=0x32f6b50)
    at ../../../../../src/lib/util/delegate.h:511
#7  sound_stream::update_view (this=<optimized out>, start=..., end=..., outputnum=<optimized out>)
    at ../../../../../src/emu/sound.cpp:742
#8  0x0000000001cba947 in sound_stream_input::update (this=0x4358980, start=..., end=...) at ../../../../../src/emu/sound.cpp:518
#9  0x0000000001cbb024 in sound_stream::update_view (this=0x33133c0, start=..., end=..., outputnum=<optimized out>, 
    outputnum@entry=0) at ../../../../../src/emu/attotime.h:99
#10 0x0000000001cbe832 in speaker_device::mix (this=0x2e58b10, leftmix=0x3404070, rightmix=0x3432e80, start=..., end=..., 
    expected_samples=960, suppress=false) at ../../../../../src/emu/speaker.cpp:70
#11 0x0000000001cbcd49 in sound_manager::update (this=0x33ec850, ptr=<optimized out>, param=<optimized out>)
    at /usr/include/c++/11/bits/stl_vector.h:1043
#12 0x0000000001c9d083 in delegate_base<void, void*, int>::operator() (args#1=<optimized out>, args#0=<optimized out>, 
    this=0x33117a8) at ../../../../../src/lib/util/delegate.h:506
#13 device_scheduler::execute_timers (this=this@entry=0x7fffffffd3c0) at ../../../../../src/emu/schedule.cpp:907
#14 0x0000000001c994ec in device_scheduler::timeslice (this=this@entry=0x7fffffffd3c0) at ../../../../../src/emu/schedule.cpp:544
#15 0x0000000001c3e707 in running_machine::run (this=this@entry=0x7fffffff7f60, quiet=quiet@entry=false)
    at ../../../../../src/emu/machine.cpp:381
#16 0x00000000006de754 in mame_machine_manager::execute (this=this@entry=0x2db2170)
    at ../../../../../src/frontend/mame/mame.cpp:269
#17 0x00000000007759b6 in cli_frontend::start_execution (this=0x7fffffffdbe0, manager=0x2db2170, args=...)
    at ../../../../../src/frontend/mame/clifront.cpp:271
#18 0x0000000000775b6e in cli_frontend::execute (this=this@entry=0x7fffffffdbe0, 
    args=std::vector of length 11, capacity 11 = {...}) at ../../../../../src/frontend/mame/clifront.cpp:287
#19 0x00000000006dc1a8 in emulator_info::start_frontend (options=..., osd=..., args=std::vector of length 11, capacity 11 = {...})
    at ../../../../../src/frontend/mame/mame.cpp:400
#20 0x00000000004f0325 in main (argc=<optimized out>, argv=<optimized out>) at ../../../../../src/osd/sdl/sdlmain.cpp:219
```

**Comment by cuavas** [comment]
Can’t reproduce in a debug build of be9cb8161a6b4cb0df551bc4c1c557ef7978d631.
