### ISSUE TITLE
floptool flopcreate segfault since mame 0.233

### ISSUE THREAD

**Issue by sairuk** [mamedev/mame#9458]
Ran into a segfault when trying out flopcreate with 0.241, so i went back through my older versions and found this was working in mame 0.232 but broke in 0.233

0.232
```
$ ./mame -version
0.232 (mame0232)
```
```
$ ./floptool flopcreate pc u35dsdd sb16.img
$ echo $?
0
$ ./floptool identify sb16.img 
sb16.img : Opus DDOS disk image
```

0.233 and above
```
$ ./mame -version
0.233 (mame0233)
```

```
$ ./floptool flopcreate pc u35dsdd sb16.img
Segmentation fault (core dumped)
```

from 0.236 which is all i have onhand compiled with symbols

```
Program received signal SIGSEGV, Segmentation fault.
0x000055555557fc44 in flopcreate (argc=<optimised out>, argv=0x7fffffffe928) at ../../../../../src/tools/floptool.cpp:237
warning: Source file is more recent than executable.
237		if(!dest_format->m_format->supports_save()) {
(gdb) bt
#0  0x000055555557fc44 in flopcreate (argc=<optimised out>, argv=0x7fffffffe928) at ../../../../../src/tools/floptool.cpp:237
#1  0x000055555557a97d in main (argc=5, argv=0x7fffffffe928) at ../../../../../src/tools/floptool.cpp:689
(gdb) 
```

**Comment by galibert** [comment]
Fixed 0e7d9c43e001c844a105fae740d370c10afc18dc.
Thanks for the report, very useful.
